---
title: "Descargables"
---

En esta página muestro trabajos presentados en **Congresos, Ponencias y cursos** sobre diversos temas. Puedes descargarlos sin problema. *Sólo te pido que los cites en tus trabajos para evitar plagio.*

### 01. Historia y economía política

> El capital es el origen de la sociedad burguesa.

-   [Descarga aquí](https://github.com/EDxBN82/Econom-a-Pol-tica) 

### 02. Análisis de Redes Sociales

> El capital social es el conjunto de recursos incrustados en las relaciones sociales utilizados por sus miembros.

-   [Descarga PDF](https://github.com/EDxBN82/Newtorks_analysis)

### 03. Democracia y teoría política

> La democracia va más allá de votar por representantes. Es una forma de vida donde la sociedad resuelve sus problemas de manera colectiva.

-   [Descarga PDF](https://github.com/EDxBN82/Teoria_politica)

### 04. Políticas públicas

> Un gobierno materializa sus programas a través de las políticas públicas. A partir de ellas, la gente decide si se queda o se va ese gobierno.

-   [Descarga PDF](https://github.com/EDxBN82/Politicas_publicas)
