<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Norberto Bustos">
<meta name="description" content="Análisis del capital burocrático de los candidatos presidenciales de Honduras en 2025.">

<title>El Capital burocratico de los candidatos a la presidencia de Honduras 2025 – n0dn | The linked data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0db67974d568b4a9c14e1974351f9748.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/simbolo_n0dn.png" alt="" class="navbar-logo light-content">
    <img src="../images/simbolo_n0dn.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">n0dn | The linked data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">🏠 Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">Sobre mi</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../descargables.html"> 
<span class="menu-text">Descargables</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#el-capital-burocrático-de-los-candidatos" id="toc-el-capital-burocrático-de-los-candidatos" class="nav-link" data-scroll-target="#el-capital-burocrático-de-los-candidatos"><span class="header-section-number">2</span> El capital burocrático de los candidatos</a></li>
  <li><a href="#el-capital-burocrático-por-partido" id="toc-el-capital-burocrático-por-partido" class="nav-link" data-scroll-target="#el-capital-burocrático-por-partido"><span class="header-section-number">3</span> El capital burocrático por partido</a>
  <ul class="collapse">
  <li><a href="#composición-del-capital-burocrático-de-los-candidatos" id="toc-composición-del-capital-burocrático-de-los-candidatos" class="nav-link" data-scroll-target="#composición-del-capital-burocrático-de-los-candidatos"><span class="header-section-number">3.1</span> Composición del capital burocrático de los candidatos</a></li>
  </ul></li>
  <li><a href="#incertidumbre-sobre-la-continuidad-y-el-retorno-de-lo-anterior" id="toc-incertidumbre-sobre-la-continuidad-y-el-retorno-de-lo-anterior" class="nav-link" data-scroll-target="#incertidumbre-sobre-la-continuidad-y-el-retorno-de-lo-anterior"><span class="header-section-number">4</span> Incertidumbre sobre la continuidad y el retorno de lo anterior</a></li>
  <li><a href="#escenarios" id="toc-escenarios" class="nav-link" data-scroll-target="#escenarios"><span class="header-section-number">5</span> Escenarios</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">El Capital burocratico de los candidatos a la presidencia de Honduras 2025</h1>
  <div class="quarto-categories">
    <div class="quarto-category">analisis</div>
    <div class="quarto-category">politica</div>
    <div class="quarto-category">capital burocrático</div>
    <div class="quarto-category">Honduras</div>
  </div>
  </div>

<div>
  <div class="description">
    Análisis del capital burocrático de los candidatos presidenciales de Honduras en 2025.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Norberto Bustos </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">25 de septiembre de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>En las elecciones generales contempladas para el 30 de noviembre 2025 en Honduras, se elegirán 1 presidente de la nación, 128 diputados para el Congreso Nacional, 20 diputados para el Congreso Centroamericano, 298 alcaldes y vice-alcaldes así como 2,128 regidores. Sin embargo, a nivel presidencial se advierte la repetición de rostros y alianzas estratégicas entre las redes políticas y sus líderes conservadores, liberales y libres.</p>
<p>Nasri Afura, será candidato por segunda ocasión consecutiva por el conservador Partido Nacional, así como Salvador Nasrala que competirá en su cuarta contienda consecutiva tras haberse desempeñado como Primer Designado o Vicepresidente de la fórmula de la actual presidenta Xiomara Castro. Por otra parte, se encuentra la candidata oficialista Rixi Moncada quien ha ocupado los Ministerios de Defensa, Finanzas y Trabajo así como gerencias de entidades descentralizadas como la Empresa Nacional de Energía Eléctrica entre otras, y quien será su primera contienda electoral. Finalmente, está la candidatura de Mario Enrique Rivera, un candidato que pretende ser un outsider del sistema político, pero en realidad ha sido regidor de Tegucigalpa, y ha sido dueño de dos medios de comunicación donde a su vez se ha desempeñado como analista político. Rivera es el único que propone que el país se anexe a Estados Unidos, en un intento desesperado y fuera de toda proporción, para erradicar la corrupción. Sin embargo, lo que mayormente destaca de los 5 candidatos son los casos de corrupción en los que han sido implicados, ya sea por fraude a la nación, desvío de recursos millonarios, cuentas en paraísos fiscales, apoyo al golpe de Estado de 2009, entre otros.</p>
<p>Honduras aparentemente se encuentra a merced de dos propouestas de gobierno: 1) la propuesta de continuidad del programa de Centro-Izquierda del partido Libre y de la red política de esquema de linaje de Manuel Zelaya y su esposa Xiomara Castro, ligadas al progresismo latinoamericano; 2) La propuesta conservadora que pretende recuperar el poder después de la extradición por narcotráfico de Juan Orlando Hernández quien fuese candidato del Partido Nacional de Honduras (PNH). Una tercera opción sería quizás la del Partido Liberal, que representa una intersección entre el Conservadurismo y el partido Libre en donde se encuentra parte de la red de Manuel Zelaya quien fuera presidente por ese partido así como de anteriores expresidentes. Por tanto, no parece ser una competencia entre diferentes programas de gobierno, sino de estilos personales, toda vez que la clase política hondureña se encuentra entrelazada y cohesionada en diferentes sectores dentro y fuera del Estado.</p>
<p>En este artículo hablaremos sobre las elecciones presidenciales de Honduras a través de las trayectorias políticas de los candidatos y pre-candidatos de los partidos para ocupar la primera magistratura. Para ello, evaluaremos el <strong>capital burocrático</strong> a partir de la metodología que hemos desarrollado en <strong>n0dn</strong> a fin de comparar la capacidad directiva de los candidatos a partir de su historial político. Como describimos en artículos anteriores, el <a href="https://www.n0dn.com/post/metodolog%C3%ADa-para-el-an%C3%A1lisis-del-capital-pol%C3%ADtico-de-los-candidatos-presidenciales"><strong>capital burocrático</strong></a> es el cúmulo de competencias, experiencia, conocimientos y relaciones que poseen los agentes dentro de una burocracia, y que les permite operar eficaz y legítimamente en el marco institucional estatal o corporativo. A partir de la sistematización de los cargos directivos según su posición en torno al poder ejecutivo es posible medir y comparar la experiencia de cualquier actor, partido o coalición política desde las guerras de Independencia hasta la actualidad. Con ello, podemos generar indicadores políticos que nos permitan comprender el alcance de los candidatos para movilizar estructuras y capitales sociales dentro y fuera del Estado y que hemos denominado capital burocrático. Por su puesto, es un esfuerzo metodológico que aun se encuentra en fase de desarrollo y se requieren aún varias pruebas y detección de errores para mejorar su calibración.</p>
<p>Nuestro análisis se divide en tres secciones: primero analizaremos los perfiles de los candidatos a fin de conocer el capital burocrático personal, posteriormente analizaremos la experiencia que suma cada partido por sus candidatos para conocer los patrones de reclutamiento de dichas instituciones. Finalmente realizaremos un análisis político sobre los resultados que arrojen la medición del capital burocrático de los dos apartados anteriores.</p>
<p>Para conocer el perfil de quienes contendrán por la presidencia de Honduras, hemos analizado las biografías de candidatas y candidatos para evaluar su trayectoria política y civil, para con ella construir sus indicadores de capital burocrático por <em>persona, partido y coalición</em>. Iniciaremos por conocer las trayectorias personales de los candidatos activos y no activos.</p>
<p>Cada partido y coalición realizó elecciones internas para designar a sus candidatos y hasta septiembre de 2025, se contempla la participación de 5 candidatos presidenciales activos y 8 precandidatos no activos. A continuación te presentamos un resumen de cada candidato activo y no activo.</p>
<section id="candidatos-por-partido-activos" class="level4" data-number="1.0.0.1">
<h4 data-number="1.0.0.1" class="anchored" data-anchor-id="candidatos-por-partido-activos"><span class="header-section-number">1.0.0.1</span> Candidatos por partido [Activos]</h4>
<p><strong><em>Rixi Ramona Moncada Godoy</em></strong> nació en Talanga, departamento de Francisco Morazán en 1965.Es abogada y financiera, con experiencia como juez y magistrada penal, y asesora en el Ministerio Público y Congreso Nacional por más de una década. Se ha desempeñado como Secretaria de Trabajo, gerente general de la Empresa Nacional de Energía Eléctrica (ENEE), consejera del Consejo Nacional Electoral (CNE), secretaria de Finanzas, y primera mujer en ocupar la Secretaría de Defensa. Ha sido militante y dirigente del Partido Libertad y Refundación (Libre) dada su cercanía con los expresidentes y esposos Manuel Zelaya y Xiomara Castro.</p>
<p><strong><em>Nelson Ávila Gutiérrez</em></strong> nació en Tegucigalpa, departamento de Francisco Morazán, en 1952. Es economista y contador público egresado de la Universidad Nacional Autónoma de Honduras (UNAH), con maestría y doctorado en economía por la Université Paris VIII, en Francia. Ha desarrollado una amplia carrera como profesor universitario e investigador internacional, además de desempeñarse como asesor del gobierno de Manuel Zelaya. Fue comisionado presidencial ante la Alternativa Bolivariana para las Américas (ALBA-Sucre) y el Banco del ALBA.</p>
<p>En el ámbito político, es fundador de la corriente 5 de Julio y del Partido Migrante, actualmente en transición al Partido Innovación y Unidad Social Demócrata (PINU-SD), por el cual es candidato presidencial en 2025. También participó activamente en la Resistencia Popular tras el golpe de Estado de 2009.</p>
<p><strong><em>Salvador Alejandro César Nasralla Salum</em></strong> Nació en Tegucigalpa, departamento de Francisco Morazán, en 1953. Es ingeniero civil industrial de formación, aunque su reconocimiento público proviene principalmente de su carrera como presentador y productor de televisión, con más de cuatro décadas. Fue fundador del Partido Anticorrupción (PAC), desde el cual lanzó su primera candidatura presidencial en 2013. Posteriormente, participó en la creación del Partido Salvador de Honduras (PSH), con el que también compitió en el escenario político nacional. En 2021 asumió el cargo de designado presidencial dentro del gobierno de Xiomara Castro.</p>
<p>Actualmente, es candidato presidencial por el Partido Liberal (PLH), desde el movimiento interno denominado “¡Vamos, Honduras!”, con el que busca proyectar una renovación dentro de una de las agrupaciones políticas más tradicionales del país. S</p>
<p><strong><em>Mario “Chano” Rivera Callejas</em></strong> es publicista y empresario del sector de la comunicación, propietario de un canal de televisión en Honduras. Aunque no existen datos públicos detallados sobre su año y lugar de nacimiento, su trayectoria se ha centrado en el ámbito empresarial, especialmente en los medios de comunicación. En política, es candidato presidencial en 2025 por el Partido Democracia Cristiana (DC), desde donde ha planteado propuestas polémicas como transformar a Honduras en un Estado Libre Asociado de los Estados Unidos, siguiendo el modelo de Puerto Rico.</p>
<p><strong><em>Nasry Juan Asfura Zablah</em></strong>, conocido popularmente como “Papi a la Orden”, nació en Tegucigalpa, departamento de Francisco Morazán, en 1958. Inició estudios de ingeniería civil, aunque no los concluyó, y posteriormente se consolidó como empresario en el sector de la construcción. Ha ocupado diversos cargos en la administración pública y en el Partido Nacional, destacando como director del Fondo Hondureño de Inversión Social, diputado del Congreso Nacional y alcalde del Distrito Central entre 2014 y 2022. También se desempeñó como designado presidencial. Su carrera política se ha visto acompañada de controversias judiciales, entre ellas acusaciones por presunto fraude y lavado de activos, aunque los procesos fueron anulados y no continuaron.</p>
</section>
<section id="precandidatos-no-activos" class="level4" data-number="1.0.0.2">
<h4 data-number="1.0.0.2" class="anchored" data-anchor-id="precandidatos-no-activos"><span class="header-section-number">1.0.0.2</span> Precandidatos [No Activos]</h4>
<p><strong><em>Rasel Antonio Tomé Flores</em></strong> nació en Olanchito, departamento de Yoro, en 1969. Es abogado y notario, graduado de la Universidad Nacional Autónoma de Honduras (UNAH). Su carrera política ha estado vinculada al Partido Libertad y Refundación (Libre), del cual es dirigente y diputado en el Congreso Nacional. Ha sido cercano al expresidente Manuel Zelaya y participó en la Resistencia Popular tras el golpe de Estado de 2009. Su perfil se caracteriza por una fuerte postura crítica hacia el bipartidismo tradicional y por su rol como operador político en la consolidación del partido Libre.</p>
<p><strong><em>Jorge Alberto Zelaya</em></strong> nació en Tegucigalpa, departamento de Francisco Morazán, en 1961. Es ingeniero civil y empresario de la construcción. Ha sido diputado en varias legislaturas por el Partido Nacional de Honduras, y se ha posicionado como un político con influencia en la zona central del país. Durante su trayectoria legislativa ha trabajado en temas de infraestructura, desarrollo local y fortalecimiento institucional. Su figura ha cobrado relevancia en la política nacional a través de su papel como opositor interno dentro de su partido y su aspiración presidencial.</p>
<p><strong><em>Ana Rosalinda García Caías</em></strong> nació en Tegucigalpa, departamento de Francisco Morazán, en 1972. Es abogada y notaria, con estudios de posgrado en derecho constitucional. Ha ocupado distintos cargos dentro de la administración pública, entre ellos ministra de la Mujer y viceministra en el área de seguridad. Su trayectoria política está ligada al Partido Nacional de Honduras, desde donde ha impulsado iniciativas en favor de los derechos de las mujeres y políticas de seguridad. En 2025 se presenta como candidata presidencial, enfatizando un discurso de fortalecimiento institucional y políticas de equidad.</p>
<p><strong><em>Carlos Urbizo Solís</em></strong> nació en Tegucigalpa en 1931. Es economista, académico y empresario, con estudios en Estados Unidos. Su trayectoria ha estado marcada por su rol como analista económico y crítico del modelo político y económico hondureño. Ha sido docente universitario, asesor empresarial y figura recurrente en medios de comunicación por sus opiniones sobre la situación económica del país. Aunque no ha tenido un papel protagónico en cargos de elección popular, se ha postulado a la presidencia con un discurso anticorrupción y de reformas estructurales en la economía y el Estado.</p>
<p><strong><em>Roberto Aníbal Martínez Lozano</em></strong> nació en Honduras en 1958. Es médico cirujano de profesión y académico en el área de la salud. Ha desempeñado cargos como rector de la Universidad Nacional Autónoma de Honduras (UNAH) y ha estado vinculado a la gestión pública en instituciones de educación y salud. Su perfil político se asocia a un enfoque técnico y académico, con propuestas centradas en el fortalecimiento de los sistemas de salud y educación. En el escenario electoral, se presenta como candidato con un discurso orientado a la modernización del Estado y la profesionalización de la administración pública.</p>
<p><strong><em>Jorge Luis Cálix Espinal</em></strong> nació en Tegucigalpa, Francisco Morazán, en 1986. Es abogado egresado de la Universidad Nacional Autónoma de Honduras (UNAH). Su carrera política se desarrolla en el Partido Libertad y Refundación (Libre), donde ha sido diputado desde 2014 y ha ejercido cargos de liderazgo en el Congreso Nacional. Su figura ha estado marcada por momentos de confrontación política, especialmente en la elección de la directiva del Congreso en 2022, que lo enfrentó con la dirigencia de Libre. En 2025 busca la presidencia con un discurso renovador y de apertura dentro del partido.</p>
<p><strong><em>Luis Orlando Zelaya Medrano</em></strong> nació en Santa Bárbara en 1967. Es ingeniero industrial con estudios en administración y liderazgo político. Ha sido presidente del Consejo Central Ejecutivo del Partido Liberal de Honduras (CCEPL) y candidato presidencial en 2017, consolidándose como uno de los líderes visibles del liberalismo moderno. Su discurso se centra en la transparencia, la lucha contra la corrupción y la modernización del Estado. En 2025 vuelve a contender por la presidencia con un mensaje de renovación del Partido Liberal y de rescate de su papel histórico en la política nacional.</p>
<p><strong><em>Maribel Espinoza</em></strong> Turcios nació en La Ceiba, Atlántida, en 1961. Es abogada y notaria, con destacada trayectoria en la defensa de los derechos humanos y el fortalecimiento democrático. Ha ejercido como asesora legal, litigante y defensora en temas de derechos constitucionales y libertades fundamentales. En política, ha sido diputada y figura clave dentro del Partido Liberal de Honduras, aunque posteriormente se integró como candidata en espacios de oposición y alianzas. Su perfil se caracteriza por la firmeza en sus posturas políticas, la defensa de la democracia y el combate a la corrupción.</p>
</section>
</section>
<section id="el-capital-burocrático-de-los-candidatos" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> El capital burocrático de los candidatos</h1>
<p>Ahora sistematizaremos la información de cada personaje para covnertirlo en un dato. Inicaremos nuestro análisis presentando los rasgos generalizados de los 13 aspirantes a candidatos presidenciales que participaron en las elecciones internas de sus partidos. Como se aprecia en la <span class="citation" data-cites="tb1-generales-kb-hnd">(<a href="#ref-tb1-generales-kb-hnd" role="doc-biblioref"><strong>tb1-generales-kb-hnd?</strong></a>)</span> que presenta la información general de los candidatos ordenados de manera descendiente por su capital burocrático, encontramos los siguientes resultados:</p>
<ul>
<li><p>La mayoría de los candidatos provienen del departamento de Francisco Morazán donde se localiza su capital, Tegucigalpa, así como de los municipios de Yoro.</p></li>
<li><p>La edad promedio es de 62 años, siendo el más joven Jorge Luis Calix con 40 años y el mayor con 82 años que fue el caso de Carlos Urbizo Solis</p></li>
<li><p>Sólo tres de los 13 casos son mujeres.</p></li>
<li><p>El Partido Liberal presentó mayor cantidad de aspirantes con 4, seguido del Nacional con 3, Libertado y Refundación 2 e Innovación y Unidad Socialdemócrata y Democracia Cristiana 1 cada uno.</p></li>
<li><p>Con respecto al capital burocrático <strong>(kb)</strong>, la media es de 402.30 kbs, siendo el menor 56 kb por el octogenario Carlos Urbizo y el mayor kb por la candidata oficialista Rixi Moncada con 1,215.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 14px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Candidato
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Edad
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Género
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Departamento de nacimiento
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Coalición
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Partido
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Candidatura activa
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Capital burocrático
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Rixi Ramona Moncada Godoy
</td>
<td style="text-align:right;">
60
</td>
<td style="text-align:left;">
Mujer
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Libertad y Refundación
</td>
<td style="text-align:left;">
Libertad y Refundacion
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
1215
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Salvatore Alejand César Nasralla Stark
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
¡Vamos Honduras!
</td>
<td style="text-align:left;">
Liberal
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
652
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Nelson Avila
</td>
<td style="text-align:right;">
73
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Innovación y Unidad
</td>
<td style="text-align:left;">
Innovación y Unidad Socialdemócrata
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
521
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Nasry Juan Asfura Zablah
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Movimiento Papi a la Orden
</td>
<td style="text-align:left;">
Nacional
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
503
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Rasel Antonio Tomé Flores
</td>
<td style="text-align:right;">
53
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Yoro
</td>
<td style="text-align:left;">
Libertad y Refundación
</td>
<td style="text-align:left;">
Libertad y Refundacion
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
433
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Roberto Aníbal Martínez Lozano
</td>
<td style="text-align:right;">
74
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Rescate y Transformación
</td>
<td style="text-align:left;">
Nacional
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
396
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Ana Rosalinda García Caías
</td>
<td style="text-align:right;">
57
</td>
<td style="text-align:left;">
Mujer
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Avanza por la Unidad y la Justicia
</td>
<td style="text-align:left;">
Nacional
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
340
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Mario Enrique Rivera Callejas
</td>
<td style="text-align:right;">
61
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Democracia Cristiana
</td>
<td style="text-align:left;">
Democracia Cristiana
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
313
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Jorge Alberto Zelaya
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Yoro
</td>
<td style="text-align:left;">
Renovación y Hunidad Nacionalista
</td>
<td style="text-align:left;">
Nacional
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
272
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Jorge Luis Cálix Espinal
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Juntos Por el Cambio
</td>
<td style="text-align:left;">
Liberal
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
241
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Luis Orlando Zelaya Medrano
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Recuperar Honduras
</td>
<td style="text-align:left;">
Liberal
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
187
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Maribel Espinoza Turcios
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:left;">
Mujer
</td>
<td style="text-align:left;">
Francisco Morazán
</td>
<td style="text-align:left;">
Todos por Honduras
</td>
<td style="text-align:left;">
Liberal
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
101
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Carlos Urbizo Solis
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Atlántida
</td>
<td style="text-align:left;">
Rescate y Transformación
</td>
<td style="text-align:left;">
Nacional
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
56
</td>
</tr>
</tbody>
</table>
<p>Tabla 1. Datos generales de los aspirantes</p>
</div>
</div>
</section>
<section id="el-capital-burocrático-por-partido" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> El capital burocrático por partido</h1>
<p>Ciertamente la acumulación de experiencia de cada partido muestra la composición de sus clase dirigente. A mayor capital burocrático dentro del Estado, mayor es su capacidad de movilización de personal, recursos e instituciones públicas para labores estratégicas. Como se aprecia en <span class="citation" data-cites="gf-partidos-hnd">(<a href="#ref-gf-partidos-hnd" role="doc-biblioref"><strong>gf-partidos-hnd?</strong></a>)</span> los partidos LIBRE, Nacional y Liberal acumulan 84.05% del de los 5230 kb, que suman todos los capitales burocráticos de los candidatos de esta elección.</p>
<p>Los aspirantes del partido Oficialista ‘LIBRE’, acumula 1,648 kb, destacando el intra-burocrático, el cual describe su experiencia dentro del poder ejecutivo nacional y que equivale a 814 kbs, casí el doble de su contrincante más cercanos que es el Partido Nacional que obtuvo en este rubro 495 kb y el partido liberal 120 kb. No obstante, destaca que Innivación y Unidad Socialdemócrata acumula 286 kb intra burocrático que duplica al obtenido por los liberales. Resulta notable además que sólo los tres principales partidos acumulen capital para-burocrático que describe la experiencia de los candidatos en otros poderes casi tan relevantes que el ejecutivo nacional, como el Congreso, la Suprema Corte, el ejército o las gubernaturas departamentales</p>
<p>El partido LIBRE vuelve a destacar por acumular mayor capital para-burocrático con 471 kb, luego el Liberal con 287 kb y el nacional con 196 kb. El capital sub-burocrático se refiere la a los cargos dentro de los partidos y alcaldías, el Liberal lidera este indicador con 520 kb, seguido del Nacional y LIBRE con 396 y 305 respectivamente, así como 233 de la Democracia Cristiana y 145 del partido Innovación social. Lo anterior sugiere una conicidiencia para todos los candidatos de coincidir en el capital sub-burocrático y llevar gran parte de su historia política en este sector, espe</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Candidatos_Honduras_2025_files/figure-html/gf-partidos-hnd-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Gráfico 1.Tipos de Capital burocrático acumulado por partidos</figcaption>
</figure>
</div>
</div>
</div>
<section id="composición-del-capital-burocrático-de-los-candidatos" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="composición-del-capital-burocrático-de-los-candidatos"><span class="header-section-number">3.1</span> Composición del capital burocrático de los candidatos</h2>
<p>Recordemos que el capital burocrático es un indicador de ese esfuerzo y capacidad en actividades directivas que le dotan del prestigio necesario para acceder a posiciones cada vez más estratégicas dentro del aparato de Estado que les permitan alcanzar los recursos necesarios para llevar a cabo los programas políticos y solventar temas de interés de su subred política. Para poder determinar qué tanto capital burocrático posee cada candidato, calculamos la desviación estándar con respecto al promedio de todos los aspirantes que es de 311.74 kb. A partir de ello, encontramos cinco clasificaciones Muy alto, Alto, Medio alto, Medio y bajo.</p>
<section id="muy-alto" class="level4" data-number="3.1.0.1">
<h4 data-number="3.1.0.1" class="anchored" data-anchor-id="muy-alto"><span class="header-section-number">3.1.0.1</span> <strong>Muy alto</strong></h4>
<p>En esta categoría destaca únicamente la candidatura de Rixi Moncada, quien, como se observa en <span class="citation" data-cites="gr2-Dist-cargos">(<a href="#ref-gr2-Dist-cargos" role="doc-biblioref"><strong>gr2-Dist-cargos?</strong></a>)</span>, acumula <strong>1,215 kb</strong>, compuestos en su mayoría por su experiencia en cargos como ministra de Estado, que representan aproximadamente el <strong>60% de su trayectoria</strong>. A ello se suma su paso por el Poder Judicial y la dirección de partidos políticos, mientras que su menor participación corresponde al ámbito empresarial. En este sentido, puede afirmarse que es la candidata con mayor capital burocrático, ya que su acumulado es más del doble respecto al del segundo candidato con mayor kb, lo que le otorga una capacidad superior de movilización de las estructuras del Estado hondureño en comparación con el resto de los aspirantes. Esta condición incrementa las probabilidades de victoria del partido oficial. Dada su experiencia en el capital intra burocrático, tiene mayor posibilidad de nombrar a personal leal y cercano que le aumente sus probabilidades de maniobra al interior del Estado en caso de llegar a la presidencia.</p>
</section>
<section id="alto" class="level4" data-number="3.1.0.2">
<h4 data-number="3.1.0.2" class="anchored" data-anchor-id="alto"><span class="header-section-number">3.1.0.2</span> <strong>Alto</strong></h4>
<p>Salvador Nasralla es el segundo mayor candidato con capital burocrático. Nasralla Stark posee <strong>652 kb</strong> siendo el 58.2% de su experiencia en la dirección de partidos políticos su mayor componente del kb, seguida de su experiencia en el ámbito empresarial con 152 kb y su experiencia como primer designado a la presidencia con 120. En este sentido, Nasralla parece contar con mayor peso en la movilización de la estructura partidista así como empresarial, pero depende en una menor medida de las decisiones del oficialismo. Al no acumular tanta experiencia en el capital intra burocrático, requerirá de acuerdos con otros actores que sí lo tengan, lo que reduciría su capacidad de maniobra política en caso de llegar a la presidencia.</p>
</section>
<section id="medio-alto" class="level4" data-number="3.1.0.3">
<h4 data-number="3.1.0.3" class="anchored" data-anchor-id="medio-alto"><span class="header-section-number">3.1.0.3</span> <strong>Medio Alto</strong></h4>
<p>Nelson Ávila, Nasri Asfura y Rasel Tomé son los candidatos que registran kb medio alto con 521, 503 y 433 kb respectivamente. El 54.8% del kb de Nelson Ávila procede de su experiencia en sus cargos como asesor económico en diferentes proyectos del presidente Manuel Zelaya, seguido de su experiencia en partidos políticos y en proyectos de sociedad civil que forman el otro 40% de su kb.</p>
<p>Por su parte, Nasri Asfura cuenta con mayor experiencia en las alcadías que representa un tercio de su capital burocrático, seguido de su experiencia en partidos políticos con 27% y 19.6% en cargos directivos en la burocracia nacional. Tanto el peso de su experiencia en la legislatura como en empresas es similar. Este candidato presenta una trayectoria mayor como administrador público local con conexiones a nivel nacional debido a su actividad partidista que le han permitido transitar entre niveles de gobierno local-nacional.</p>
<p>En el caso de Rasel Tomé, con 433 kb 40.4% del capital burocrático procede del poder legislativo, y el otro 60% se reparte en proporciones similares entre sus cargos en cargos ministeriales, judiciales y en los partidos políticos. Esto indica que tiene más peso su capacidad como intermediario que como administrador público.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Candidatos_Honduras_2025_files/figure-html/gr2-Dist-cargos-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Gráfico 2. Distribución por tipo de kb por candidato</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="medio" class="level4" data-number="3.1.0.4">
<h4 data-number="3.1.0.4" class="anchored" data-anchor-id="medio"><span class="header-section-number">3.1.0.4</span> <strong>Medio</strong></h4>
<p>Un elemento que es notable en los actores con capital medio es la poca variabilidad de su capital burocrático. Quizás el caso más emblemático es Roberto Anibal Martínez quien posee el 100% de sus 396 kb está compuesto sólo por sus cargos en los ministerios de Energía y Educación, lo cual hace suponer que es actor de confianza de de un actor político pero sin llegar a ser estratégico para la subred, un alfil si se permite la analogía ajedrecística.</p>
<p>Por otra parte, Ana Rosalinda García registra que el 82.3% de sus 340 kb corresponden a cargos directivos en las empresas privadas y el otro 20% en sociedad civil, lo que la describe como una candidata sin experiencia dentro del aparato de Estado. Lo anterior indica que pudiera conducirse en función de algún grupo político que utiliza su prestigio pero que tiene control sobre su agenda política. Es el problema recurrente en los <em>outsiders</em>.</p>
<p>En el caso de Mario Enrique Ribera Callejas se registra que el 59.1% de sus 313 kb corresponden a sus cargos directivos en los partidos políticos seguido de su experiencia en las empresas privadas que representa el 25.5% de su experiencia que es mayor que sus puesto como regidor de Tegucigalpa que representa el 15.3%. Aunque su discurso aparenta ser un outsider, en el análisis de su capital burocrático lo reporta como el candidato más cercano al promedio.</p>
<p>Jorge Alberto Zelaya registra que el 51.4% de su kb se localiza en el poder legislativo, 30.8% en el sector empresarial y 17.6% por su cargo como regidor de la captital.</p>
<p>Jorge Luis Calix es otro ejemplo de poca variabilidad del capital burocrático, pues se ha desempeñado en mayor medida en el poder legislativo, el cual representa 95.8% de su kb, en cambio su particicpación en las movilizaciones contra el golpe de 2009 representa el 5%. Por la centralización de su kb en el legislativo, probablemente actue como broker entre dos o más organizaciones y cuya relevancia justo depende de controlar el flujo del capital social entre las subredes que intermedia.</p>
</section>
<section id="bajo" class="level4" data-number="3.1.0.5">
<h4 data-number="3.1.0.5" class="anchored" data-anchor-id="bajo"><span class="header-section-number">3.1.0.5</span> <strong>Bajo</strong></h4>
<p>Finalmente describiremos a los tres aspirantes que registraron el kb más bajo. Luis Orlando Zelaya, quien apesar de haber sido candidato presidencial por el Partido Liberal en 2021 y quedar en tercer lugar, registra 187 kb, de los cuales 50% se debe a su trayectoria como líder del partido y como candidato a la presidencia; 40% se debe a su cargo como rector del UNITEC y el 10% restante en su participación como militante del movimiento de <em>“Coalición de Unidad de Oposición Fuera Dictadura”</em>, para expulsar Juan Orlando Hernández del poder.</p>
<p>Maribel Espinoza con 101 kb registra un historial balanceado entre sus cargos como legisladora y presidenta del partido Liberal con 55.4% por sus cargos como diputada y como vicepresidenta nacional de su partido junto con Luis Alberto Zelaya quien era el presidente.</p>
<p>Finalmente se registra que Carlos Urbizo quien a pesar de ser el candidato con mayor edad (82 años) es a su vez el aspirtante con menor experiencia directiva burocrática, pues registró 56 kb. Gran parte de su trayectoria la ha dedicado al ámbito académico como asesor económico, por lo que no registra un cargo directivo relevante, salvo en su incorporación en 1997 como sucesor designado de la candidata Nora Gunera que representa 55.4% de su kb y el resto por su apoyo como asesor del gobierno interino de Roberto Micheleti tras el golpe de Estado de aquel año.</p>
</section>
</section>
</section>
<section id="incertidumbre-sobre-la-continuidad-y-el-retorno-de-lo-anterior" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Incertidumbre sobre la continuidad y el retorno de lo anterior</h1>
<p>Honduras enfrenta problemas muy importantes de corrupción, Estado de Derecho, falta de transparencia, pobreza y desigualdad, sin embargo su red política dirigente parece no dar muestras de modificar estructuralmente dicha problemática. De los 5.8 millones de electores, la mayoría de los cuales son hombres y con mayor propoción entre los 31 y 40 años de edad, las opiniones sobre intención de voto aun se encuentran divididas. De acuerdo con las encuestas de opinión muestran datos dispares debido a que una parte de ellos muestra a Moncada como la ganadora y otras a Nasralla como ganador. Todo depende de la cercanía de las encuestadoras con el candidato.</p>
<p>Las encuestas sobre las elecciones presidenciales de Honduras en 2025 muestran una carrera altamente competitiva entre los principales candidatos, con variaciones en los resultados según la encuestadora y la fecha de realización. Rixi Moncada, candidata del Partido Libre, lidera en varias encuestas con un 44.9% de intención de voto según TResearch, seguida por Salvador Nasralla del Partido Liberal con un 27.5% y Tito Asfura del Partido Nacional con un 23.4%. Sin embargo, otros estudios presentan un escenario más cercano: un promedio nacional de encuestas por Dato World indica que Tito Asfura lidera con un 31.1%, seguido por Rixi Moncada con un 29.9% y Salvador Nasralla con un 29.8%. En mayo de 2025, Expedition Strategies reportó a <strong>Nasralla como líder con un 25.2% de intención de voto, seguido por Asfura con un 21.4% y Moncada con un 16%</strong>.</p>
<p>En cuanto a la percepción de victoria, <strong>Nasralla obtiene un 30.8% de los votos, Moncada un 25.9% y Asfura un 21%</strong>. Aunque Moncada es percibida como la candidata que representa el cambio positivo por un 43.2% de los encuestados, frente al 30.1% que lo considera Nasralla, el 5.5% de los encuestados aún no ha definido su voto. Las encuestas también indican que el 37% de los encuestados en mayo de 2025 eran indecisos, lo que refleja una alta incertidumbre en el escenario electoral. Las elecciones se desarrollarán en una sola vuelta, lo que aumenta la posibilidad de que cualquiera de los tres principales candidatos pueda ganar, con un escenario legislativo fragmentado y sin mayoría clara.</p>
</section>
<section id="escenarios" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Escenarios</h1>
<section id="continuidad-y-autonomía" class="level4" data-number="5.0.0.1">
<h4 data-number="5.0.0.1" class="anchored" data-anchor-id="continuidad-y-autonomía"><span class="header-section-number">5.0.0.1</span> Continuidad y autonomía</h4>
<p>Por un lado, el partido oficial cuya subred se desprende de la familia del expresidente Manuel Zelaya y de su esposa Xiomara Castro, la actual presidenta de Honduras han orientado sus políticas públicas para la reducción de la pobreza, corrupción y crimen organizado. También han estrechado acuerdos con las fuerzas militares quienes les han brindado el apoyo institucional más eficiente dentro del aparato de Estado, sin llegar a establecer un estado militar. Su candidata, amiga muy cercana de la pareja Rixi Moncada aparece como la favorita para ganar las elecciones, en algunas encuestas. Para ella sería conveniente aprovechar el contexto en el cual los partidos de oposición se encuentran fragmentados y divididos por personalidades y que carecen de un plan de gobierno claro y elocuente para el futuro.</p>
<p>Si Moncada logra convencer al electorado para continuar con las políticas de centro izquierda y aprovechar su capital burocrático para movilizar a las redes del aparato de Estado, tiene tres opciones para fortalecer su gobierno dependiendo de los resultados electorales:</p>
<ol type="1">
<li><em>Amplio margen de victoria</em>: Radicalizar sus políticas públicas en materia de combate a la pobreza y desigualdad, logrando aumentar el salario mínimo el cual es el más bajo del continente. Fortalecer la posición del Estado para mejorar las condiciones de vida de la población a través de programas de redistribución de la riqueza vía impuestos, así como el impulso estatal para la industrialización del país, aprovechando sus ventajas energéticas. Adicionalmente, implementar políticas de cero tolerancia a la corrupción, incremento de la transparencia y generar una reforma judicial que le permita desbloquear la impunidad en el sistema de justicia, el cual es su principal lastre desde hace varias décadas. De lograrlo, podría sentar un precedente institucional y por tanto, estructural para fortalecer la posición de Libre para los próximos 10 años.</li>
<li><em>Poco margen de victoria</em>: Esto podría aplicarlo en caso de que el escenario de los 3 tercios electorales aparezca en las elecciones de noviembre, que podrían fortalecer las posiciones conservadoras que a su vez podrían mantenerse fragmentadas entre sí. Moderar su discurso para lograr acuerdos con la oposición que le permitan establecer pocos pero importantes políticas estructurales, como la reducción de la pobreza e inseguridad. La gobernabilidad en el corto plazo estaría comprometida por la habilidad política de sus operadores y dirigentes.</li>
<li><em>Pierde las elecciones</em>: Negociar posiciones estratégicas con el gobierno de Nasralla para mantenerse dentro del gobierno y fortalecer sus posiciones legislativas en los diferentes departamentos. Le permitiría renovar parte de su diriencia y mejorar los perfiles para las siguientes elecciones presidenciales.</li>
</ol>
</section>
<section id="regreso-y-dependencia" class="level4" data-number="5.0.0.2">
<h4 data-number="5.0.0.2" class="anchored" data-anchor-id="regreso-y-dependencia"><span class="header-section-number">5.0.0.2</span> Regreso y dependencia</h4>
<p>Por su parte, Salvador Nasralla quien es el candidato de oposición con mayor probabilidad de ganar, puede aporvechar su discurso de combate a la corrupción y a su vez su posición de intermediario entre el gobierno actual y las subredes conservadoras. El aparador de las políticas de seguridad de Bukele han sido muy efectivas en la reducción de inseguridad en las calles salvadoreñas, a pesar de que ello implique pasar por alto el debido proceso judicial para encarcelar a los verdaderos delincuentes. Nasralla ha emitido comunicados moderados al respecto, para atraer a los electores abyectos al cambio radical que comunmente forman el grueso del electorado.</p>
<p>Si Nasralla logra obtener la victoria en estas elecciones, tendría dos opciones para generar su nuevo gobierno:</p>
<p>1. <em>Amplio margen de victoria</em>: Integrar un gobierno de coaliciones dada su posición de intermediario entre la subred del gobierno de Libre y el Partido Nacional, lo cual le permitiría aumentar la gobernabilidad en el corto plazo, pero dada la divergencia de opiniones ese gobierno sería altamente volátil. Tendría que contar con el apoyo de las oligarquías y terratenientes locales, pero sin dejar de lado la opción de acercamiento con la clase dirigente norteamericana quien le pediría alinear sus políticas a la visión fascista del gobierno de Donald Trump. Su carta más importante sería la detención de la emigración hacia Estados Unidos, lo cual exige la militarización de su frontera.</p>
<ol start="2" type="1">
<li><em>Poco margen de victoria:</em> Integrar un gobierno de derechas conformado por militantes del partido Nacional, Libre y Liberal principalmente con el objetivo de procurar generar una visión consistente y conservadora, que les permita favorecer los intereses de las oligarquías terratenientes y acercarse a la clase dirigente norteamericana, y con ello aprovechar la oleada conservadora del presidente Donald Trump. Sin embargo, el tiempo con el que contaría con el apoyo de Trump sería acortado, dado que el mandatario estadounidense estará en el gobierno hasta el 2028 sin oportunidad de reelección, es decir, sólo 2 años de su mandato podría contar con ese apoyo.</li>
<li><em>Pierde las elecciones:</em> Si pierde estas elecciones el partido Nacional, estaría jugandose su carta de supervivencia. La fragmentación al interior y los escandalos de corrupción no permiten generar espacioes de cohesión entre sus subredes partidistas, por lo que otra derrota significaría la atomización de sus liderazgos.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2021-2026 n0dn | The linked Data. Todos los derechos reservados.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/n0dn_">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/norberto-bustos/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="mailto:n0dn.info@proton.me">
<p>n0dn.info@proton.me</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>