---
title: "El problema de la gestión de las crisis económicas"
author: "Eduardo BxN"
date: 2023-05-04
categories: [crisis financieras]
description: "Contenido migrado desde n0dn.com. Revisa y completa el texto, imágenes y enlaces."
image: ""
---

El manejo de las crisis económicas implica grandes esfuerzos de coordinación entre actores que pertenecen a diferentes redes de poder interrelacionadas, pero que defienden intereses diversos para mantener un sistema económico y político que beneficia a las élites capitalistas o al Estado respectivamente [1](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818). A la capacidad de coordinar intereses, presiones y luchas entre múltiples redes de poder se denomina gobernabilidad [2](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

Históricamente, las burocracias han tenido la responsabilidad de encontrar soluciones eficientes a las crisis económicas y políticas. Sin embargo, dado que los Estados proceden de manera funcional a los bloques de dominación para procurar apoyo, las condiciones oligárquicas del manejo de la política han llevado a que los bloques de dominación cambien de actores y relaciones en el tiempo [3](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

## Bloques de dominación

Se denomina bloques de dominación a todas aquellas redes de agentes políticos y económicos que concentran los suficientes recursos estratégicos como para afectar de manera importante el Estado capitalista. La relevancia de los bloques históricos de dominación depende del desarrollo histórico del Estado capitalista y pueden ser de dos tipos:

\- políticas si controlan los recursos del aparato de Estado,y ;

\- económicas, si controlan recursos de las grandes industrias, comercio y bancos.

Partimos del supuesto de que los bloques históricos de dominación responden a las formas adaptativas del sistema de relaciones político-económicas, en función de los cambios producidos por la evolución del Estado capitalista dependiente.

La formación de bloques en el poder como les denomina Nicos Poulantzas se diferencia de las alianzas políticas por dos variables: La primera es el carácter contradictorio de los vínculos "en

relación con una forma de Estado y en un estadío particular" que implica "sacrificios mutuos" que implican una ampliación relativa de la unidad entre las clases sociales y las fracciones de esas clases. La segunda se refiere a la naturaleza contradictoria de la unidad que implica generar una alianza histórica en función de un modelo de Estado, que a diferencia de una alianza política no sería posible mas que en ciertos momentos de la lucha política de clases4.

## Bloques de poder politico

Los bloques de poder politico por tanto, corresponden a *una transformación de la forma de Estado* y no sólo a la búsqueda de ciertos intereses particulares y temporales que constituyen las *alianzas*. La burocracia en este sentido es una clase subalterna a las clases dominantes, pero que por su cercanía con el aparato de estado detenta el poder político, compuesta por diferentes fracciones de clase que dependen del grado jerárquico al que pertenezcan, y que la organización relativa al aparato de Estado funciona a partir de la autonomía relativa del resto de instituciones sociales y económicas y que por tanto, un cambio o crisis de Estado implica también la participación de los agentes del Estado[6](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

## Bloques de poder económico 

Por su parte, nos referimos a los

bloques de poder económico (BPE) a todas aquellas redes de agentes estratégicos vinculados con las grandes empresas y bancos privados, particularmente vinculados a veinticuatro familias de grandes empresarios que en conjunto llegan a concentrar más del 40 por ciento del ingreso nacional, en estricto sentido, nos referiremos a los oligopolios. Cómo señala Marx, estos oligopolios o monopolios son el resultado tanto de la concentración como de la centralización del capital a través de consorcios, firmas, corporaciones holdings .

Las estrategias engendradas desde ambos bloques de dominación que permitan modos adaptativos de gobernabilidad burguesa parten de la correlación de fuerzas entre clases dominantes, como la alta burocracia, los grandes empresarios y banqueros, dada su El Estado ocupa una posición central en el control de los recursos económicos estratégicos frente a las clases trabajadoras. Por lo tanto, la definición de una gobernabilidad que permita el mantenimiento de las condiciones de dominación en función de las necesidades de reproducción del sistema de acumulación de capital por parte de las oligarquías preexistentes se gesta dentro de la lucha de clases, donde el Estado es un agente regulador mediante sus agentes de control, coerción y financiamiento.

## Gobernabilidad burguesa

En este sentido, la gobernabilidad burguesa responde a la necesidad de encontrar intereses comunes acordes con el desarrollo del Estado capitalista en sus funciones históricas básicas [7](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

Flatow y Huisken describen tres funciones básicas del Estado capitalista en relación con la burguesía empresarial y financiera que comprenden factores como:

a\) proteger la propiedad en todas sus formas

b\) crear condiciones en las que los ingresos puedan aumentar a través de la competencia, y

c\) regular el curso de la acumulación de capital para que las crisis y los ciclos económicos se eliminen en la medida de lo posible.

En consecuencia, la vinculación entre las redes políticas y económicas resulta fundamental para la gobernabilidad del Estado capitalista, así como para el establecimiento de políticas económicas que permitan la reproducción del capital en función de las oligarquías nacionales y al mismo tiempo permitan que el Estado catalice las demandas sociales mediante políticas públicas, infraestructura y otros programas, evitando afectar los intereses de los bloques de dominación económica.

## Notas

[^1] El manejo de las crisis económicas implica grandes esfuerzos de coordinación entre actores que pertenecen a diferentes redes de poder interrelacionadas, pero que defienden intereses diversos para mantener un sistema económico y político que beneficia a las élites capitalistas o al Estado respectivamente [1](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818). A la capacidad de coordinar intereses, presiones y luchas entre múltiples redes de poder se denomina gobernabilidad [2](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

[^1]: El manejo de las crisis económicas implica grandes esfuerzos de coordinación entre actores que pertenecen a diferentes redes de poder interrelacionadas, pero que defienden intereses diversos para mantener un sistema económico y político que beneficia a las élites capitalistas o al Estado respectivamente [1](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818). A la capacidad de coordinar intereses, presiones y luchas entre múltiples redes de poder se denomina gobernabilidad [2](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

    Históricamente, las burocracias han tenido la responsabilidad de encontrar soluciones eficientes a las crisis económicas y políticas. Sin embargo, dado que los Estados proceden de manera funcional a los bloques de dominación para procurar apoyo, las condiciones oligárquicas del manejo de la política han llevado a que los bloques de dominación cambien de actores y relaciones en el tiempo [3](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

    ## Bloques de dominación

    Se denomina bloques de dominación a todas aquellas redes de agentes políticos y económicos que concentran los suficientes recursos estratégicos como para afectar de manera importante el Estado capitalista. La relevancia de los bloques históricos de dominación depende del desarrollo histórico del Estado capitalista y pueden ser de dos tipos:

    \- políticas si controlan los recursos del aparato de Estado,y ;

    \- económicas, si controlan recursos de las grandes industrias, comercio y bancos.

    Partimos del supuesto de que los bloques históricos de dominación responden a las formas adaptativas del sistema de relaciones político-económicas, en función de los cambios producidos por la evolución del Estado capitalista dependiente.

    La formación de bloques en el poder como les denomina Nicos Poulantzas se diferencia de las alianzas políticas por dos variables: La primera es el carácter contradictorio de los vínculos "en

    relación con una forma de Estado y en un estadío particular" que implica "sacrificios mutuos" que implican una ampliación relativa de la unidad entre las clases sociales y las fracciones de esas clases. La segunda se refiere a la naturaleza contradictoria de la unidad que implica generar una alianza histórica en función de un modelo de Estado, que a diferencia de una alianza política no sería posible mas que en ciertos momentos de la lucha política de clases4.

    ## Bloques de poder politico

    Los bloques de poder politico por tanto, corresponden a *una transformación de la forma de Estado* y no sólo a la búsqueda de ciertos intereses particulares y temporales que constituyen las *alianzas*. La burocracia en este sentido es una clase subalterna a las clases dominantes, pero que por su cercanía con el aparato de estado detenta el poder político, compuesta por diferentes fracciones de clase que dependen del grado jerárquico al que pertenezcan, y que la organización relativa al aparato de Estado funciona a partir de la autonomía relativa del resto de instituciones sociales y económicas y que por tanto, un cambio o crisis de Estado implica también la participación de los agentes del Estado[6](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

    ## Bloques de poder económico 

    Por su parte, nos referimos a los

    bloques de poder económico (BPE) a todas aquellas redes de agentes estratégicos vinculados con las grandes empresas y bancos privados, particularmente vinculados a veinticuatro familias de grandes empresarios que en conjunto llegan a concentrar más del 40 por ciento del ingreso nacional, en estricto sentido, nos referiremos a los oligopolios. Cómo señala Marx, estos oligopolios o monopolios son el resultado tanto de la concentración como de la centralización del capital a través de consorcios, firmas, corporaciones holdings .

    Las estrategias engendradas desde ambos bloques de dominación que permitan modos adaptativos de gobernabilidad burguesa parten de la correlación de fuerzas entre clases dominantes, como la alta burocracia, los grandes empresarios y banqueros, dada su El Estado ocupa una posición central en el control de los recursos económicos estratégicos frente a las clases trabajadoras. Por lo tanto, la definición de una gobernabilidad que permita el mantenimiento de las condiciones de dominación en función de las necesidades de reproducción del sistema de acumulación de capital por parte de las oligarquías preexistentes se gesta dentro de la lucha de clases, donde el Estado es un agente regulador mediante sus agentes de control, coerción y financiamiento.

    ## Gobernabilidad burguesa

    En este sentido, la gobernabilidad burguesa responde a la necesidad de encontrar intereses comunes acordes con el desarrollo del Estado capitalista en sus funciones históricas básicas [7](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

    Flatow y Huisken describen tres funciones básicas del Estado capitalista en relación con la burguesía empresarial y financiera que comprenden factores como:

    a\) proteger la propiedad en todas sus formas

    b\) crear condiciones en las que los ingresos puedan aumentar a través de la competencia, y

    c\) regular el curso de la acumulación de capital para que las crisis y los ciclos económicos se eliminen en la medida de lo posible.

    En consecuencia, la vinculación entre las redes políticas y económicas resulta fundamental para la gobernabilidad del Estado capitalista, así como para el establecimiento de políticas económicas que permitan la reproducción del capital en función de las oligarquías nacionales y al mismo tiempo permitan que el Estado catalice las demandas sociales mediante políticas públicas, infraestructura y otros programas, evitando afectar los intereses de los bloques de dominación económica.

    ## Notas

    [1](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818) Nos referimos al Estado para denominar al conjunto de organizaciones políticas que centralizan el poder político de forma categórica. En cambio, nos referimos al aparato político al conjunto de instituciones instrumentales como la burocracia, el ejército, el presupuesto, aparatos de justicia y mecanismos de gobierno. Mena, Marco A. \[Comp.\], *Gestión de crisis*, Escuela de Administración Pública del Gobierno del Distrito Federal, Ed.Siglo XXI, México, 2011.

    [2](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818) Los recursos disponibles son aquellos bienes, capitales o servicios que los actores sociales disponen de manera formal en un momento determinado. En cambio, los recursos potenciales son aquellos que no tienen en ese momento pero que existe la posibilidad de obtenerlos ya sea por medio de una compra, intercambio, enajenación o expropiación.

    [3](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Atlhusser, basado en la teoría leninista del Estado como aparato al servicio de la clase dominante, concluye que "toda lucha política de clases gira al rededor del Estado", entendida por dos factores, uno "la conservación del poder" como objetivo de la lucha política de clases y el "aparato de Estado por otra". Althusser, L., *Ideología y aparatos ideológicos del Estado. Freud y Lacan*, Ed. Nueva Visión, 2003, Buenos Aires.

    [4](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Poulantzas, N., *Poder político y clases sociales en el Estado capitalista*, Ed. Siglo I, 1978, México, pp. 311-313

    [5](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Dussel, E. *20 Tesis de Política*, Ed. Siglo XXI, CREFAL, 2010, México.

    [6](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Poulantzas, N., "Las transformaciones actuales del Estado, la crisis política y la crisis del Estado, en Poulantzas, N., Buci-Glucksmann, C., Vincent, J.M., Hirsch, J., Bruhnhoff, S., *El marxismo y la crisis del Estado*, Universidad Autónoma de Puebla, 1977, México, pp. 52 y 53

    [7](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Flatow, S. y Huisken, F., "Zum problem der Ableitung des bürgerlichen Staates: die oberflache der bürerlicheGesellshaft, der Staat, und die allgemein Rahmenbedingugnen der Production, en PROKLA Núm. 7, 1973, Berlín oriental.

Históricamente, las burocracias han tenido la responsabilidad de encontrar soluciones eficientes a las crisis económicas y políticas. Sin embargo, dado que los Estados proceden de manera funcional a los bloques de dominación para procurar apoyo, las condiciones oligárquicas del manejo de la política han llevado a que los bloques de dominación cambien de actores y relaciones en el tiempo [3](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

## Bloques de dominación

Se denomina bloques de dominación a todas aquellas redes de agentes políticos y económicos que concentran los suficientes recursos estratégicos como para afectar de manera importante el Estado capitalista. La relevancia de los bloques históricos de dominación depende del desarrollo histórico del Estado capitalista y pueden ser de dos tipos:

\- políticas si controlan los recursos del aparato de Estado,y ;

\- económicas, si controlan recursos de las grandes industrias, comercio y bancos.

Partimos del supuesto de que los bloques históricos de dominación responden a las formas adaptativas del sistema de relaciones político-económicas, en función de los cambios producidos por la evolución del Estado capitalista dependiente.

La formación de bloques en el poder como les denomina Nicos Poulantzas se diferencia de las alianzas políticas por dos variables: La primera es el carácter contradictorio de los vínculos "en

relación con una forma de Estado y en un estadío particular" que implica "sacrificios mutuos" que implican una ampliación relativa de la unidad entre las clases sociales y las fracciones de esas clases. La segunda se refiere a la naturaleza contradictoria de la unidad que implica generar una alianza histórica en función de un modelo de Estado, que a diferencia de una alianza política no sería posible mas que en ciertos momentos de la lucha política de clases4.

## Bloques de poder político

Los bloques de poder politico por tanto, corresponden a *una transformación de la forma de Estado* y no sólo a la búsqueda de ciertos intereses particulares y temporales que constituyen las *alianzas*. La burocracia en este sentido es una clase subalterna a las clases dominantes, pero que por su cercanía con el aparato de estado detenta el poder político, compuesta por diferentes fracciones de clase que dependen del grado jerárquico al que pertenezcan, y que la organización relativa al aparato de Estado funciona a partir de la autonomía relativa del resto de instituciones sociales y económicas y que por tanto, un cambio o crisis de Estado implica también la participación de los agentes del Estado[6](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

## Bloques de poder económico 

Por su parte, nos referimos a los

bloques de poder económico (BPE) a todas aquellas redes de agentes estratégicos vinculados con las grandes empresas y bancos privados, particularmente vinculados a veinticuatro familias de grandes empresarios que en conjunto llegan a concentrar más del 40 por ciento del ingreso nacional, en estricto sentido, nos referiremos a los oligopolios. Cómo señala Marx, estos oligopolios o monopolios son el resultado tanto de la concentración como de la centralización del capital a través de consorcios, firmas, corporaciones holdings .

Las estrategias engendradas desde ambos bloques de dominación que permitan modos adaptativos de gobernabilidad burguesa parten de la correlación de fuerzas entre clases dominantes, como la alta burocracia, los grandes empresarios y banqueros, dada su El Estado ocupa una posición central en el control de los recursos económicos estratégicos frente a las clases trabajadoras. Por lo tanto, la definición de una gobernabilidad que permita el mantenimiento de las condiciones de dominación en función de las necesidades de reproducción del sistema de acumulación de capital por parte de las oligarquías preexistentes se gesta dentro de la lucha de clases, donde el Estado es un agente regulador mediante sus agentes de control, coerción y financiamiento.

## Gobernabilidad burguesa

En este sentido, la gobernabilidad burguesa responde a la necesidad de encontrar intereses comunes acordes con el desarrollo del Estado capitalista en sus funciones históricas básicas [7](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818).

Flatow y Huisken describen tres funciones básicas del Estado capitalista en relación con la burguesía empresarial y financiera que comprenden factores como:

a\) proteger la propiedad en todas sus formas

b\) crear condiciones en las que los ingresos puedan aumentar a través de la competencia, y

c\) regular el curso de la acumulación de capital para que las crisis y los ciclos económicos se eliminen en la medida de lo posible.

En consecuencia, la vinculación entre las redes políticas y económicas resulta fundamental para la gobernabilidad del Estado capitalista, así como para el establecimiento de políticas económicas que permitan la reproducción del capital en función de las oligarquías nacionales y al mismo tiempo permitan que el Estado catalice las demandas sociales mediante políticas públicas, infraestructura y otros programas, evitando afectar los intereses de los bloques de dominación económica.

## Notas

[1](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818) Nos referimos al Estado para denominar al conjunto de organizaciones políticas que centralizan el poder político de forma categórica. En cambio, nos referimos al aparato político al conjunto de instituciones instrumentales como la burocracia, el ejército, el presupuesto, aparatos de justicia y mecanismos de gobierno. Mena, Marco A. \[Comp.\], *Gestión de crisis*, Escuela de Administración Pública del Gobierno del Distrito Federal, Ed.Siglo XXI, México, 2011.

[2](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818) Los recursos disponibles son aquellos bienes, capitales o servicios que los actores sociales disponen de manera formal en un momento determinado. En cambio, los recursos potenciales son aquellos que no tienen en ese momento pero que existe la posibilidad de obtenerlos ya sea por medio de una compra, intercambio, enajenación o expropiación.

[3](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Atlhusser, basado en la teoría leninista del Estado como aparato al servicio de la clase dominante, concluye que "toda lucha política de clases gira al rededor del Estado", entendida por dos factores, uno "la conservación del poder" como objetivo de la lucha política de clases y el "aparato de Estado por otra". Althusser, L., *Ideología y aparatos ideológicos del Estado. Freud y Lacan*, Ed. Nueva Visión, 2003, Buenos Aires.

[4](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Poulantzas, N., *Poder político y clases sociales en el Estado capitalista*, Ed. Siglo I, 1978, México, pp. 311-313

[5](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Dussel, E. *20 Tesis de Política*, Ed. Siglo XXI, CREFAL, 2010, México.

[6](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Poulantzas, N., "Las transformaciones actuales del Estado, la crisis política y la crisis del Estado, en Poulantzas, N., Buci-Glucksmann, C., Vincent, J.M., Hirsch, J., Bruhnhoff, S., *El marxismo y la crisis del Estado*, Universidad Autónoma de Puebla, 1977, México, pp. 52 y 53

[7](https://www.notion.so/El-problema-de-la-gesti-n-de-las-crisis-econ-micas-a5b9c2eafea24733a87b809642878818)Flatow, S. y Huisken, F., "Zum problem der Ableitung des bürgerlichen Staates: die oberflache der bürerlicheGesellshaft, der Staat, und die allgemein Rahmenbedingugnen der Production, en PROKLA Núm. 7, 1973, Berlín oriental.
