<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Norberto Bustos">
<meta name="description" content="Análisis del capital burocrático de los candidatos presidenciales de Argentina en 2023.">

<title>El Capital burocratico de los candidatos a la presidencia de Argentina en 2023 – n0dn | The linked data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0db67974d568b4a9c14e1974351f9748.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/simbolo_n0dn.png" alt="" class="navbar-logo light-content">
    <img src="../images/simbolo_n0dn.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">n0dn | The linked data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">🏠 Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">Sobre mi</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../descargables.html"> 
<span class="menu-text">Descargables</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#los-22-aspirantes-a-la-presidencia-de-argentina" id="toc-los-22-aspirantes-a-la-presidencia-de-argentina" class="nav-link active" data-scroll-target="#los-22-aspirantes-a-la-presidencia-de-argentina"><span class="header-section-number">1</span> Los 22 aspirantes a la presidencia de Argentina</a>
  <ul class="collapse">
  <li><a href="#capital-burocrático-por-bloques-y-partidos-políticos" id="toc-capital-burocrático-por-bloques-y-partidos-políticos" class="nav-link" data-scroll-target="#capital-burocrático-por-bloques-y-partidos-políticos"><span class="header-section-number">1.1</span> Capital burocrático por bloques y partidos políticos</a></li>
  </ul></li>
  <li><a href="#el-capital-burocrático-de-los-candidatos-ganadores-de-las-primarias." id="toc-el-capital-burocrático-de-los-candidatos-ganadores-de-las-primarias." class="nav-link" data-scroll-target="#el-capital-burocrático-de-los-candidatos-ganadores-de-las-primarias."><span class="header-section-number">2</span> El capital burocrático de los candidatos ganadores de las primarias.</a></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión"><span class="header-section-number">3</span> Conclusión</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">El Capital burocratico de los candidatos a la presidencia de Argentina en 2023</h1>
  <div class="quarto-categories">
    <div class="quarto-category">analisis</div>
    <div class="quarto-category">politica</div>
    <div class="quarto-category">capital burocrático</div>
    <div class="quarto-category">Argentina</div>
  </div>
  </div>

<div>
  <div class="description">
    Análisis del capital burocrático de los candidatos presidenciales de Argentina en 2023.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Norberto Bustos </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2 de octubre de 2023</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Las elecciones primarias en Argentina del 14 de agosto de 2023 reflejaron el descontento debido al manejo de la política fiscal durante la pandemia de COVID-19 y la renegociación de la deuda con el FMI, contraída durante el gobierno de Mauricio Macri (2015-2019). El presidente Alberto Fernández (2019-2023) heredó el país con una tasa de inflación de alrededor del 60% anual, una crisis cambiaria significativa y la posibilidad de incumplir con los acreedores de la deuda externa. La discordia en el gabinete de Fernández sobre las negociaciones con el Fondo Monetario Internacional (FMI) resultó en la destitución de Martín Guzmán como ministro de Economía, reemplazado por el entonces presidente de la Cámara de Diputados, Sergio Massa, quien prometió cambios estructurales para resolver la situación.</p>
<p>La desaprobación al gobierno de Fernández se acentuó tras perder las elecciones legislativas de 2021, donde obtuvo el 35% de los votos frente a la coalición “Unidos por el Cambio,” que se convirtió en la fuerza principal con el 43% de los votos. Además, la vicepresidenta Cristina Fernández fue declarada culpable de delitos relacionados con el mal manejo de recursos públicos, aunque no pudo cumplir su condena debido a apelaciones y el fuero constitucional. Todo esto fomentó una confrontación más intensa por parte de sus detractores.</p>
<p>El bloque de derecha “Juntos por el Cambio,” que gobernó durante el mandato de Macri, se reorganizó y logró el segundo lugar en las elecciones PASO con la candidatura de Patricia Bullrich, superando al ministro de Economía, Sergio Massa, del bloque oficialista “Juntos hacemos historia.” Sin embargo, el primer lugar en las PASO fue para la propuesta neoliberal “La Libertad Avanza” de Javier Milei, que obtuvo el 30% de los votos. Según las encuestas, algunos argentinos podrían seguir a este político de extrema derecha y caer en promesas mágicas pero insostenibles, lo que podría poner fin al peronismo y desencadenar la desaparición del Banco Central, ministerios de gobierno, programas sociales y la moneda argentina. ¿No hemos visto esto antes en las décadas de los 70 y 90 con el neoliberalismo?</p>
<p>Los datos de las PASO muestran que las diferencias entre los tres bloques son del 2.8%, lo que no indica una tendencia clara a favor de ninguno. Milei deberá negociar con el bloque de Macri para obtener suficientes votos del bloque no peronista, mientras que Massa podría buscar acuerdos con algunos grupos de “Juntos por el Cambio” y sectores de izquierda para mejorar su competitividad. En cualquier caso, la situación sugiere que <em>algo debe cambiar en Argentina.</em></p>
<p>En <strong>n0dn</strong>nos hemos propuesto comparar los perfiles de los 22 aspirantes a la candidatura presidencial que participaron en las elecciones PASO, con miras a la contienda programada para el 22 de octubre de 2023. Estos aspirantes provienen de diversas listas y bloques, y nuestro objetivo es ofrecer una herramienta de análisis basada en la medición del capital burocrático, lo que nos permitirá evaluar su experiencia en cargos directivos, tanto dentro como fuera del Estado.</p>
<section id="los-22-aspirantes-a-la-presidencia-de-argentina" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="los-22-aspirantes-a-la-presidencia-de-argentina"><span class="header-section-number">1</span> Los 22 aspirantes a la presidencia de Argentina</h2>
<p>Argentina, un país con una larga historia de altibajos económicos y problemas políticos crónicos, ha vivido una sorpresa en estas elecciones. Se trata de un candidato que carece de experiencia en cargos políticos tradicionales pero que tiene fuertes vínculos con gobiernos de derecha y propuestas poco convencionales.</p>
<p>Desde el año 2003, las elecciones presidenciales en Argentina han alternado entre candidatos peronistas y no peronistas, con enfoques distintos en políticas sociales y económicas. La crisis del 2001 dificultó la creación de políticas de Estado a largo plazo, ya que la rápida sucesión de gobiernos impidió una continuidad en las políticas públicas.</p>
<p>Dentro del peronismo, existen dos corrientes principales. Por un lado, está el peronismo nacionalista de izquierda, representado por figuras como Néstor Kirchner, Cristina Fernández, Daniel Scioli y Sergio Massa. Estos gobiernos se caracterizaron por la nacionalización de sectores estratégicos, la promoción de la industria nacional y mejoras en los derechos sociales. Sin embargo, incluso con la estabilidad económica lograda durante el gobierno de Kirchner, se vieron afectados por escándalos de corrupción, especialmente entre funcionarios cercanos a Cristina Fernández.</p>
<p>Por otro lado, está el peronismo neoliberal liderado por Carlos Menem (1989-1999), que implementó una serie de reformas orientadas al mercado, incluyendo la privatización de empresas estatales y la desregulación financiera. También estableció un régimen de convertibilidad peso-dólar de Estados Unidos para combatir la hiperinflación de los años ochenta, pero esto tuvo un alto costo en la producción industrial, que cayó del 42% al 28% del PIB, y un aumento significativo en la deuda externa, que pasó de 65 mil millones a 151 mil millones de dólares. La presidencia de Menem sentó las bases para la crisis financiera que estalló en 2001 durante el mandato de Fernando de la Rúa, su sucesor.</p>
<p>En la Tabla 1, se pueden observar los resultados de las últimas cinco elecciones, donde predominan los bloques peronistas y no peronistas. El capital burocrático promedio de los candidatos ganadores es de 781.53 kb, con un porcentaje promedio de votos obtenidos del 39.96%.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 10px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Elaborado por: n0dn | The linked data
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Información básica
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="4">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Actividad electoral
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Adscripción política
</div>
</th>
</tr>
<tr>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Año
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Candidato
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Partido
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Votos
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
kb
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Éxito
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Adscripción
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2003
</td>
<td style="text-align:left;">
Carlos Menem
</td>
<td style="text-align:left;">
PJ
</td>
<td style="text-align:right;">
24.45
</td>
<td style="text-align:right;">
775
</td>
<td style="text-align:left;">
Ganador
</td>
<td style="text-align:left;">
Peronista
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2003
</td>
<td style="text-align:left;">
Ricardo López Murphy
</td>
<td style="text-align:left;">
MFR
</td>
<td style="text-align:right;">
16.37
</td>
<td style="text-align:right;">
455
</td>
<td style="text-align:left;">
Perdedor
</td>
<td style="text-align:left;">
No peronista
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2007
</td>
<td style="text-align:left;">
Cristina Fernández
</td>
<td style="text-align:left;">
AFV
</td>
<td style="text-align:right;">
45.28
</td>
<td style="text-align:right;">
574
</td>
<td style="text-align:left;">
Ganador
</td>
<td style="text-align:left;">
Peronista
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2007
</td>
<td style="text-align:left;">
Ricardo López Murphy
</td>
<td style="text-align:left;">
RecCrec
</td>
<td style="text-align:right;">
1.43
</td>
<td style="text-align:right;">
455
</td>
<td style="text-align:left;">
Perdedor
</td>
<td style="text-align:left;">
No peronista
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2011
</td>
<td style="text-align:left;">
Cristina Fernández
</td>
<td style="text-align:left;">
AFV
</td>
<td style="text-align:right;">
47.98
</td>
<td style="text-align:right;">
749
</td>
<td style="text-align:left;">
Ganador
</td>
<td style="text-align:left;">
Peronista
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2011
</td>
<td style="text-align:left;">
Hermes Binner
</td>
<td style="text-align:left;">
AFAP
</td>
<td style="text-align:right;">
9.72
</td>
<td style="text-align:right;">
726
</td>
<td style="text-align:left;">
Perdedor
</td>
<td style="text-align:left;">
No peronista
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2015
</td>
<td style="text-align:left;">
Daniel Scioli
</td>
<td style="text-align:left;">
FPV
</td>
<td style="text-align:right;">
37.08
</td>
<td style="text-align:right;">
913
</td>
<td style="text-align:left;">
Perdedor
</td>
<td style="text-align:left;">
Peronista
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2015
</td>
<td style="text-align:left;">
Mauricio Macri
</td>
<td style="text-align:left;">
Cambiemos
</td>
<td style="text-align:right;">
34.15
</td>
<td style="text-align:right;">
1239
</td>
<td style="text-align:left;">
Ganador
</td>
<td style="text-align:left;">
No peronista
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
2019
</td>
<td style="text-align:left;">
Mauricio Macri
</td>
<td style="text-align:left;">
PRO
</td>
<td style="text-align:right;">
41.42
</td>
<td style="text-align:right;">
1648
</td>
<td style="text-align:left;">
Perdedor
</td>
<td style="text-align:left;">
No peronista
</td>
</tr>
</tbody>
</table>
<p>Tabla 1. Candidatos presidenciales peronistas y no peronistas y capital burocrático</p>
</div>
</div>
<p>Desde 2009, las elecciones PASO han sido el método democrático para seleccionar candidatos presidenciales y legislativos. Para calificar, los aspirantes deben obtener al menos el 1.5% de los votos emitidos. En estas elecciones primarias, Sergio Massa, del bloque “Unión por la Patria”, sorprendió al lograr el tercer lugar con un 27.27% de los votos, lo que plantea dudas sobre el futuro del proyecto kirchnerista. La credibilidad de este proyecto se ha visto afectada por la gestión de la crisis financiera heredada del gobierno de Mauricio Macri y por los escándalos de corrupción que involucran a la Vicepresidenta y ex Presidenta, Cristina Fernández, en el caso del Grupo Austral. A pesar de las sospechas de mal uso de recursos públicos, estas acusaciones no han tenido un impacto significativo debido al fuero de la vicepresidenta y a las numerosas apelaciones presentadas.</p>
<p>Por otro lado, Patricia Bullrich, candidata del bloque de derecha “Juntos por el Cambio”, se ubicó en el segundo lugar de las preferencias con un 28.28%, según las encuestas finales. La ex ministra de Seguridad, Seguridad Social y Trabajo durante el gobierno de Macri logró recuperar la confianza en la propuesta neoliberal, a pesar de los resultados desfavorables relacionados con el endeudamiento interno y la controvertida gestión de la negociación con los fondos buitre en la Bolsa de Valores de Nueva York.</p>
<p>La mayor sorpresa provino de la propuesta neoliberal radical de Javier Milei, quien obtuvo un 30.04% de las preferencias. Sus propuestas de privatización de los bienes nacionales, los servicios de salud y educación, la eliminación del Banco Central y la dolarización de la economía argentina llamaron la atención de los votantes. Sin embargo, muchos olvidaron que medidas similares ya se habían implementado durante el gobierno de la dictadura militar y el de Menem, lo que resultó en crisis financieras y políticas recurrentes. A pesar de sus estrechas conexiones con políticos de esa época, Milei se presenta como el principal crítico de la “casta peronista”. Esta crítica ha generado divisiones entre quienes lo respaldan y quienes lo culpan por la crisis financiera actual.</p>
<section id="capital-burocrático-por-bloques-y-partidos-políticos" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="capital-burocrático-por-bloques-y-partidos-políticos"><span class="header-section-number">1.1</span> Capital burocrático por bloques y partidos políticos</h3>
<p>La experiencia en cargos directivos es fundamental para conocer las capacidades relativas al manejo de la administración pública y del gobierno. Este factor que denominamos capital burocrático (kb), permite medir dicha experiencia por bloque, partido y aspirante. En las elecciones primarias argentinas se registraron 22 aspirantes dentro de 15 bloques de partidos políticos. De ellos, por género fueron 18 hombres (81.8 %), 3 mujeres (13.6%) y 1 mujer trans (4.5%). Sin embargo, de los cinco candidatos que pasarán a contender en la elección presidencial, 3 de ellos son varones (60%) y 2 mujeres (40%), como se describirá más adelante.</p>
<p>En relación al capital burocrático de los aspirantes, según se refleja en la Tabla 3, el bloque “Hacemos por Nuestro País” muestra el indicador más alto con 1210 kb, seguido por los aspirantes de “Juntos por el Cambio” con 994 kb, “Principios y Valores” con 745 kb, y “Unidos por la Patria” con 523 kb. En contraste, los bloques con candidatos de menor capital burocrático son el derechista “LiberAr” con 70 kb y el izquierdista “MAS” con 45 kb.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>La media del capital burocrático de los 22 aspirantes es de <strong>344.27 kb</strong></p>
</div>
</div>
<p>Al analizar a los tres aspirantes con el mayor capital burocrático (kb), como se muestra en la Tabla 3, notamos que el bloque “Hacemos por nuestro país”, que presentó únicamente la candidatura de Juan Schiaretti, registró el mayor capital burocrático entre los aspirantes, alcanzando los 1,210 kb. A pesar de obtener solo un 3.83% de los votos en las primarias, logró asegurarse un lugar en la siguiente ronda para competir por la presidencia. Le sigue Horacio Rodríguez Larreta, del bloque “Juntos por el Cambio”, con 1,193 kb, aunque no logró obtener el porcentaje de votos necesario para la nominación dentro de su bloque. Sergio Massa, candidato del bloque oficialista “Unidos por la Patria”, ocupó el tercer lugar en cuanto al capital burocrático, con 927 kb y un 21.41% de la votación, lo que le permitirá avanzar hacia las elecciones presidenciales. Lo más destacado en el kb de estos tres candidatos es su experiencia como ministros de Estado (intra-burocrático), combinada con cargos en gobiernos provinciales, legislaturas (para-burocrático), y su participación en la fundación o dirección de partidos políticos.</p>
<p>Por otro lado, los tres aspirantes con menor capital burocrático, como se detalla en la Tabla 4, son, en orden ascendente, Manuela Castañeira del bloque del “MAS”, con 45 kb, ya que solo cuenta con experiencia en el ámbito de las organizaciones civiles. Le sigue la candidata trans Reyna Xiomara Ibañez con 49 kb y un 0.01% de los votos, y en tercer lugar se encuentra el candidato del bloque derechista “LiberAR”, con 50 kb y un 0.03% de los votos. La característica más destacada de estos tres candidatos es que las dos últimas candidatas tienen experiencia en militancia o “acompañamiento”, pero no en la dirección de organizaciones civiles. En el caso de Nazareno Etchepare, la información sobre su currículum en Internet es limitada, y solo se pudo encontrar que es fundador y dirigente de la agrupación política Demos.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 10px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
Elaborado por: n0dn | The linked data
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="4">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Información básica
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Afiliación política
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Actividad electoral
</div>
</th>
</tr>
<tr>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Candidato
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Edad
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Género
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Entidad de nacimiento
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Bloque
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Estrategia
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Activo
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Capital burocrático
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Votos
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Juan Schiaretti
</td>
<td style="text-align:right;">
74
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
Córdoba
</td>
<td style="text-align:left;">
Hacemos por nuestro país
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
si
</td>
<td style="text-align:right;">
1210
</td>
<td style="text-align:right;">
3.83
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Horacio Antonio Rodríguez Larreta
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Juntos por el cambio
</td>
<td style="text-align:left;">
Recupera
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
1193
</td>
<td style="text-align:right;">
11.30
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Sergio Massa
</td>
<td style="text-align:right;">
51
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Unidos por la Patria
</td>
<td style="text-align:left;">
Mantiene
</td>
<td style="text-align:left;">
si
</td>
<td style="text-align:right;">
927
</td>
<td style="text-align:right;">
21.41
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Patricia Bulrich
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:left;">
mujer
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Juntos por el cambio
</td>
<td style="text-align:left;">
Recupera
</td>
<td style="text-align:left;">
si
</td>
<td style="text-align:right;">
795
</td>
<td style="text-align:right;">
16.99
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Guillermo Moreno
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Principios y Valores
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
745
</td>
<td style="text-align:right;">
0.77
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Myriam Bregman
</td>
<td style="text-align:right;">
51
</td>
<td style="text-align:left;">
mujer
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Frente de Izquierda
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
si
</td>
<td style="text-align:right;">
353
</td>
<td style="text-align:right;">
1.87
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Mempo Giardinelli
</td>
<td style="text-align:right;">
76
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
Chaco
</td>
<td style="text-align:left;">
PJ
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
288
</td>
<td style="text-align:right;">
0.05
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Gabriel Solano
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Frente de Izquierda
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
247
</td>
<td style="text-align:right;">
0.79
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Jesús Escobar
</td>
<td style="text-align:right;">
52
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
Chubut
</td>
<td style="text-align:left;">
Libres
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
233
</td>
<td style="text-align:right;">
0.65
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Marcelo Ramal
</td>
<td style="text-align:right;">
69
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Politica_Obrera
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
203
</td>
<td style="text-align:right;">
0.26
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Andrés Passamonti
</td>
<td style="text-align:right;">
60
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
APA
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
194
</td>
<td style="text-align:right;">
0.05
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Javier Gerardo Milei
</td>
<td style="text-align:right;">
53
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Libertad Avanza
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
si
</td>
<td style="text-align:right;">
183
</td>
<td style="text-align:right;">
30.00
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Raúl Castells
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
Santa Fe
</td>
<td style="text-align:left;">
MIJD
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
155
</td>
<td style="text-align:right;">
0.11
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Alejandro César Biondini
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
FPL
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
0.21
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Santiago Cuneo
</td>
<td style="text-align:right;">
53
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
MIJD
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
146
</td>
<td style="text-align:right;">
0.24
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Raúl Albarracín
</td>
<td style="text-align:right;">
42
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
Tucumán
</td>
<td style="text-align:left;">
Comp_Vecinal
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
139
</td>
<td style="text-align:right;">
0.24
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Juan Grabois
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
Unidos por la Patria
</td>
<td style="text-align:left;">
Mantiene
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
119
</td>
<td style="text-align:right;">
5.87
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Ramiro Vasena
</td>
<td style="text-align:right;">
78
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
LiberAR
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
90
</td>
<td style="text-align:right;">
0.06
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Martín Ayerbe Ortíz
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
PJ
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
60
</td>
<td style="text-align:right;">
0.04
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Nazareno Etcheparre
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:left;">
hombre
</td>
<td style="text-align:left;">
C.A. Buenos Aires
</td>
<td style="text-align:left;">
LiberAR
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
0.03
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Reyna Xiomara Ibañez
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:left;">
trans
</td>
<td style="text-align:left;">
Santa Fe
</td>
<td style="text-align:left;">
PJ
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:right;">
0.01
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(11, 59, 11, 255) !important;">
Manuela Castañeira
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:left;">
mujer
</td>
<td style="text-align:left;">
Entre Ríos
</td>
<td style="text-align:left;">
MAS
</td>
<td style="text-align:left;">
Alterna
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
0.36
</td>
</tr>
</tbody>
</table>
<p>Tabla 2. Datos generales de los aspirantes</p>
</div>
</div>
<p>Ciertamente, el capital burocrático de los aspirantes es un indicador que evidencia la desigualdad en la experiencia de los actores políticos que compiten por el mismo cargo público. Como se observa en la gráfica 1, solo 4 bloques están por encima de la media de kb, y representan a las fuerzas tradicionales que ya han gobernado el país. Los otros 12 bloques presentan candidatos con experiencia directiva política por debajo de la media y que nunca han ocupado cargos ejecutivos. En este sentido, la competencia con actores experimentados en la administración pública se concentra en 4 bloques.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2023-10-02-capital-burocratico-argentina-2023_files/figure-html/tb3-kb-candidatos-arg-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Gráfico 1. Capital burocrático por bloque electoral que participó en las PASO</figcaption>
</figure>
</div>
</div>
</div>
<p>La distinción entre candidatos orgánicos y no orgánicos en el contexto del aparato de Estado argentino se basa en la acumulación de capital intra, para, y sub-burocrático. Los candidatos orgánicos son aquellos que han adquirido experiencia en estas esferas, mientras que los no orgánicos solo tienen experiencia exa y ana-burocrática.</p>
<p>Los bloques “Hacemos por nuestro país”, “Juntos por el Cambio”, “Principios y Valores”, y “Unidos por la Patria” son las agrupaciones políticas que presentan candidatos orgánicos del aparato de Estado. Por otro lado, los bloques “Frente de Izquierda”, “Libres”, “Política Obrera”, “APA”, y “Libertad Avanza” son agrupaciones políticas cuyos candidatos poseen capital burocrático localizado en el poder legislativo y en los partidos políticos, aunque siguen siendo considerados orgánicos. En cambio, los bloques “MIJD”, “FPL”, “Comp Vecinal”, “PJ”, “LiberAr”, y “MAS” presentan candidatos no orgánicos, ya que su capital burocrático proviene de organizaciones de la sociedad civil, sindicatos o empresas privadas.</p>
<p>Un aspecto destacado es la presencia de tres agrupaciones con candidatos que cuentan con experiencia ana-burocrática en organizaciones de insurgencia o movimientos revolucionarios, en particular, ex militantes de izquierda peronista que lucharon clandestinamente durante la dictadura militar. Un ejemplo de esto es Patricia Bullrich, candidata de Juntos por el Cambio y ex ministra en varias carteras durante la administración de Mauricio Macri, quien en su juventud militó en movimientos y partidos de izquierda durante la dictadura militar.</p>
</section>
</section>
<section id="el-capital-burocrático-de-los-candidatos-ganadores-de-las-primarias." class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="el-capital-burocrático-de-los-candidatos-ganadores-de-las-primarias."><span class="header-section-number">2</span> El capital burocrático de los candidatos ganadores de las primarias.</h2>
<p>De los 22 aspirantes, solamente cinco lograron obtener más del 3 por ciento de los votos emitidos en las elecciones primarias. El capital burocrático de los candidatos ganadores del primarias. Solamente cinco lograron obtener más del 3 por ciento de los votos emitidos en las elecciones primarias, lo que es necesario para competir por la presidencia en las elecciones de octubre próximo. Estos cinco candidatos son Juan Schiaretti, Sergio Massa, Patricia Bullrich, Myriam Bregman y Javier Milei. A excepción de Bregman y Milei, el resto de los candidatos son considerados políticos tradicionales.</p>
<p>Como se puede observar en la tabla 6, el candidato más votado en las primarias, Javier Milei, es quien posee el menor capital burocrático de los cinco finalistas. Contrario a lo que su campaña propone, Milei no se clasifica como un candidato no orgánico o, como algunos periodistas lo llaman, “outsider”, ya que registra 56 kb-para debido a su cargo de legislador por Buenos Aires y 95 kb-sub por su rol como dirigente y fundador del partido Libertad Avanza. Por otro lado, la abogada y defensora de víctimas de la dictadura y trabajadores, Myriam Bregman, fue la candidata con menos votos, obteniendo el 1.87% de los sufragios. No obstante, ha sido la única voz crítica al gobierno de Alberto Fernández desde una perspectiva de izquierda militante y como representante legislativa, acumulando así 353 kb.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2023-10-02-capital-burocratico-argentina-2023_files/figure-html/gr2-kb-candidato-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Gráfico 2. Capital burocrático por candidato</figcaption>
</figure>
</div>
</div>
</div>
<p>En cuanto a la composición del capital burocrático, encontramos un factor común para los cinco candidatos: su experiencia en el poder legislativo y la dirección de partidos políticos. Sin embargo, la diferencia más significativa radica en que tres candidatos tienen experiencia intra-burocrática debido a su trabajo como ministros o secretarios de Estado, destacando Sergio Massa y Patricia Bullrich con una experiencia similar de 484 y 429 kb-intra, respectivamente. Por su parte, Juan Schiaretti posee la mayor experiencia para-burocrática con 792 kb-para, gracias a su experiencia en el gobierno y en el poder legislativo.</p>
</section>
<section id="conclusión" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="conclusión"><span class="header-section-number">3</span> Conclusión</h2>
<p>La contienda presidencial en Argentina se librará entre candidatos profesionales de la política y un político aficionado. El capital burocrático de los cinco candidatos finalistas muestra que Javier Milei, quien lidera en intención de votos y podría ganar la elección, es el candidato con menos experiencia, tanto dentro como fuera del Estado.</p>
<p>En comparación con los 22 aspirantes registrados, Milei se encuentra por debajo del promedio, solo superado por 7 aspirantes con menos experiencia política. Esto nos lleva a considerar que, para lograr los acuerdos necesarios, tendrá que apoyarse en otros actores con mayor capital político que le permitan llevar a cabo los cambios que propone, lo cual será complicado de negociar debido a su baja conexión con el Estado.</p>
<p>Lo anterior podría ser visto por otros políticos profesionales de derecha como una oportunidad para acercarse a Milei y formar parte de su gabinete, incluso peronistas que trabajaron en el gobierno de Menem, a quien Milei ha manifestado su admiración. La paradoja radica en la dificultad de llevar a cabo el desmantelamiento del aparato de Estado con un bajo capital burocrático, ya que requiere habilidades y experiencia que actualmente Milei no posee</p>
<p>la aceptación del electorado que es insuficiente para gobernar cuando se carece de estructura política para moverse dentro y fuera del Estado. A menos que pida estructura prestada de la red política que Milei denomina “casta”.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Si deseas descargar la base del capital burocrático de aspirantes a la presidencia de la Argentina, visita la sección <em>Descargables &gt; Análisis de redes</em> y da click en el enlace</strong></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/n0dn\.github\.io\/n0dn\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2021-2026 n0dn | The linked Data. Todos los derechos reservados.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/n0dn_">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/norberto-bustos/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="mailto:n0dn.info@proton.me">
<p>n0dn.info@proton.me</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>