<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Norberto Bustos">
<meta name="description" content="Análisis del capital burocrático de los candidatos presidenciales de Chile en 2025.">

<title>Capital burocrático de los aspirantes a la presidencia de Chile 2025 – n0dn | The linked data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-68a6f960dedeaaa5d8db067cc717a4f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/simbolo_n0dn.png" alt="" class="navbar-logo light-content">
    <img src="../images/simbolo_n0dn.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">n0dn | The linked data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">🏠 Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">Sobre mi</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../descargables.html"> 
<span class="menu-text">Descargables</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a>
  <ul class="collapse">
  <li><a href="#quiénes-son-ls-aspirantes-a-la-presidencia-de-chile-en-2025" id="toc-quiénes-son-ls-aspirantes-a-la-presidencia-de-chile-en-2025" class="nav-link" data-scroll-target="#quiénes-son-ls-aspirantes-a-la-presidencia-de-chile-en-2025"><span class="header-section-number">1.1</span> ¿Quiénes son l@s aspirantes a la presidencia de Chile en 2025?</a>
  <ul class="collapse">
  <li><a href="#perfiles-y-trayectorias" id="toc-perfiles-y-trayectorias" class="nav-link" data-scroll-target="#perfiles-y-trayectorias"><span class="header-section-number">1.1.1</span> Perfiles y trayectorias</a></li>
  <li><a href="#el-capital-burocrático-de-los-aspirantes" id="toc-el-capital-burocrático-de-los-aspirantes" class="nav-link" data-scroll-target="#el-capital-burocrático-de-los-aspirantes"><span class="header-section-number">1.1.2</span> El capital burocrático de los aspirantes</a></li>
  </ul></li>
  <li><a href="#capital-burocrático-de-las-coaliciones" id="toc-capital-burocrático-de-las-coaliciones" class="nav-link" data-scroll-target="#capital-burocrático-de-las-coaliciones"><span class="header-section-number">1.2</span> Capital burocrático de las coaliciones</a></li>
  <li><a href="#capital-burocrático-por-persona" id="toc-capital-burocrático-por-persona" class="nav-link" data-scroll-target="#capital-burocrático-por-persona"><span class="header-section-number">1.3</span> Capital burocrático por persona</a></li>
  </ul></li>
  <li><a href="#la-lucha-entre-redes-políticas-el-clan-emergente-vs-la-casta-hereditaria" id="toc-la-lucha-entre-redes-políticas-el-clan-emergente-vs-la-casta-hereditaria" class="nav-link" data-scroll-target="#la-lucha-entre-redes-políticas-el-clan-emergente-vs-la-casta-hereditaria"><span class="header-section-number">2</span> La lucha entre redes políticas: El <em>clan emergente</em> vs la <em>casta hereditaria</em></a>
  <ul class="collapse">
  <li><a href="#dinámica-del-capital-burocrático" id="toc-dinámica-del-capital-burocrático" class="nav-link" data-scroll-target="#dinámica-del-capital-burocrático"><span class="header-section-number">2.0.1</span> Dinámica del capital burocrático</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Capital burocrático de los aspirantes a la presidencia de Chile 2025</h1>
  <div class="quarto-categories">
    <div class="quarto-category">analisis</div>
    <div class="quarto-category">politica</div>
    <div class="quarto-category">capital burocrático</div>
    <div class="quarto-category">Chile</div>
  </div>
  </div>

<div>
  <div class="description">
    Análisis del capital burocrático de los candidatos presidenciales de Chile en 2025.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Norberto Bustos </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">22 de agosto de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Después del declive de la Concertación de Partidos por la Democracia y de los partidos de la extrema derecha tradicional (UDI y RN) que surgieron tras el retorno a la democracia a finales de la década de 1980, se configuró un nuevo periodo partidista en donde la red política histórica encontró nuevos espacios. Con el ascenso a la presidencia de Gabriel Boric, se esperó un rompimiento con las políticas neoliberales como las causantes de los descontentos sociales de los estudiantes, trabajadores asalariados y demás sectores de las amplias mayorías los cuales vieron agrabada su situación durante la represión durante el periodo de la pandemia durante el último año de gobierno de Sebastián Piñera. Sin embargo, los cambios no fueron tan profundos y radicales como se esperaba. Ganó la moderación y el sectarismo. Ello avivó las esperanzas de los partidos de la extrema derecha y de las redes políticas pinochetistas quienes hoy ven grandes posibilidades de volver a gobernar con José Antonio Kast. Sin embargo, la carta fuerte de la izquierda oficial - alianza de la izquierda tradicional y nuevos partidos vinculados a Boric- es la ex sindicalista y funcionaria comunista Jeannete Jara. La polarización no sólo es ideolígica, sino programática y podría derivar en el avance de los derechos de los trabajadores, reducción de la desigualdad y una agenda progresista en favor de los derechos humanos si Jara gana las elecciones, o el retorno de políticas represivas, favorables a los holdings financieros bajo una agenda de seguridad nacional a través de José Antonio Kast.</p>
<p>En este artículo compararemos la capacidad directiva de los aspirantes a la presidencia de Chile a partir de sus trayectorias dentro y fuera del aparato de Estado que denominamos <em>capital burocrático</em>. Con ello, podremos medir su capacidad de dirección en caso de llegar a la presidencia a partir de su experiencia en los cargos directivos en donde han participado desde el inicio de su carrera política. La carrera por la presidencia se construye desde la adolescencia. Además, veremos sus vínculos con otros actores políticos y la relevancia de los mismos dentro de la red política histórica. Los vínculos son tan o más importantes que la capacidad directiva, además de que muestra tendencias de comportamientos en cluster que derivan en programas políticos.</p>
<section id="quiénes-son-ls-aspirantes-a-la-presidencia-de-chile-en-2025" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="quiénes-son-ls-aspirantes-a-la-presidencia-de-chile-en-2025"><span class="header-section-number">1.1</span> ¿Quiénes son l@s aspirantes a la presidencia de Chile en 2025?</h2>
<p>Las elecciones presidenciales de Chile en 2025 constituyen un hito central en la historia política reciente del país, marcando un momento crucial para definir el futuro político, social y económico tras años de profundos cambios estructurales y demandas ciudadanas. Convocadas para el 16 de noviembre de 2025, complementadas con elecciones parlamentarias, estas contiendas electorales buscan elegir al sucesor del presidente Gabriel Boric, en un contexto de alta participación ciudadana impulsada por la inscripción automática y la obligatoriedad del voto. El ambiente político se caracteriza por una polarización creciente, un electorado más diverso y la emergencia de nuevos actores políticos, factores que complejizan la disputa democrática.</p>
<p>El bloque oficialista, conformado por la coalición Unidad por Chile, ha optado por la vía de primarias para seleccionar a su candidato presidencial, privilegiando la legitimidad interna y la unidad frente a una oposición fragmentada. La realización de primarias el 29 de junio de 2025 fue fundamental para consolidar una candidatura que represente la diversidad ideológica de esta coalición, que incluye desde fuerzas tradicionalmente de centro-izquierda hasta el Partido Comunista. Este proceso refleja la complejidad de los desafíos sociales que Chile enfrenta, como la reforma policial, la educación, el sistema de pensiones y la estabilidad económica, que exigen un liderazgo que logre cohesionar distintas visiones.</p>
<p>En oposición, la derecha y la extrema derecha presentan candidatos en primera vuelta, reflejando un espectro político plural y la fragmentación del voto conservador, pero exhibiendo una fortaleza significativa en las encuestas y en su base electoral. Esto genera un escenario donde la primera vuelta presidencial será decisiva para definir si es necesaria una segunda vuelta y cuáles serán las alianzas posteriores. Además, existen múltiples candidatos independientes que, aunque enfrentan el desafío de reunir firmas para su inscripción, aportan variedad y amplitud al proceso electoral, en sintonía con la creciente demanda ciudadana de nuevas representaciones.</p>
<p>El debate electoral en Chile 2025 se articula alrededor de temas cruciales como la seguridad pública, el desarrollo económico inclusivo, la descentralización, la política exterior y la profundización democrática. Los candidatos deberán responder no solo a los reclamos tradicionales sino también a aspiraciones emergentes de una juventud politizada y de grupos sociales históricamente marginados. De esta manera, la elección presidencial es a su vez un reflejo de las tensiones sociales y culturales que atraviesan el país, involucrando no solo la elección de un líder sino la definición de un proyecto país.</p>
<p>Finalmente, las elecciones de 2025 en Chile representan un ejercicio democrático clave para consolidar la estabilidad política y social en un contexto de incertidumbre global y local. Más allá de los resultados y candidatos, este proceso evidencia la vitalidad y complejidad del sistema democrático chileno, obligando a las fuerzas políticas a dialogar, negociar y construir consensos que permitan enfrentar los retos en la próxima década.</p>
<section id="perfiles-y-trayectorias" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="perfiles-y-trayectorias"><span class="header-section-number">1.1.1</span> Perfiles y trayectorias</h3>
<p>Para conocer el perfil de quienes contendrán por la presidencia de Chile, hemos analizado 9 biografías de candidatas y candidatos a fin de medir y comparar su capital burocrático con el objetivo de conocer su experiencia en la dirección de cargos dentro del Estado.</p>
<p>Representantes de coaliciones y partidos [Activos]</p>
<p><strong><em>Jeannette Alejandra Jara Román</em></strong> (Partido Comunista / Unidad por Chile - oficialismo): Abogada nacida en Santiago en 1974, proveniente de un barrio popular de Conchalí. Su trayectoria política se inició en las Juventudes Comunistas y ha ocupado cargos públicos como ministra del Trabajo en el gobierno de Gabriel Boric. Su campaña se distingue por su énfasis en la justicia social y la defensa de los derechos laborales y sociales. Jara ganó la primaria oficialista y representa la continuidad y profundización de las reformas sociales iniciadas en el actual gobierno.</p>
<p><strong><em>José Antonio Kast Rits</em></strong>&nbsp;(Partido Republicano - derecha/extrema derecha): Abogado y político de derecha nacido en 1966 en Santiago. Ha sido diputado en múltiples periodos y es fundador del Partido Republicano de Chile. Kast ha sido candidato en varias elecciones presidenciales, caracterizándose por posiciones conservadoras en materia económica, social y de seguridad. Representa una propuesta política que recalca la defensa del orden de tiempos de la dictadura y valores tradicionales.</p>
<p><strong><em>Ximena Cecilia Rincón González</em></strong>&nbsp;(Concepción, 5 de julio de 1967): Abogada y política chilena. Fue senadora por la Región del Maule y presidenta del Senado entre 2021 y 2022. Ha sido ministra en carteras como Secretaría General de la Presidencia y Trabajo. En 2022 renunció al Partido Demócrata Cristiano (PDC) y fundó el Partido Demócratas, del cual es presidenta.</p>
<p><strong><em>Eveline Rose Matthei Fornet</em></strong>&nbsp;(Santiago, 11 de noviembre de 1953): Economista y política de derecha. Fue alcaldesa de Providencia entre 2016 y 2024. Militó en Renovación Nacional, luego en Unión Demócrata Independiente (UDI). Ha tenido un perfil político confrontacional que ha ido suavizando con el tiempo.</p>
<p><strong><em>Johannes Maximilian Kaiser Barents von Hohenhagen&nbsp;o Johannes Maximilian Kaiser Barents von Hohenhagen</em></strong> (Santiago, 5 de enero de 1976): Youtuber y político de derecha ultraconservadora, fundador del Partido Nacional Libertario. Diputado desde 2022. Se define como paleolibertario, social-conservador y crítico de políticas como las vacunas COVID-19 y la inmigración irregular.</p>
<p>Independientes y partidos minoritarios</p>
<p><strong><em>Marco Enriquez Ominami</em></strong> (Santiago, 12 de junio de 1973): Político, cineasta y filósofo chileno. Fue diputado y fundador del Partido Progresista. Ha sido candidato presidencial en varias elecciones, logrando buenos resultados. También es conocido por su trabajo en cine y televisión.</p>
<p><strong><em>Franco Aldo Parisi Fernandez</em></strong> (Santiago, 25 de agosto de 1967): Economista e ingeniero comercial, fundador y líder del Partido de la Gente. Ha sido candidato presidencial en 2013 y 2021, con perfil populista y programas radiales y televisivos sobre economía.</p>
<p><strong><em>Harold Alfred Mayne-Nicholls Sacul</em></strong> (Antofagasta, 27 de julio de 1961): Periodista y dirigente de fútbol. Fue presidente de la Federación de Fútbol de Chile y de la ANFP. También trabajó en FIFA y tiene formación en administración de empresas.</p>
<p><strong><em>Eduardo Antonio Artés Brichetti</em></strong> (El Tambo, San Vicente de Tagua Tagua, 25 de octubre de 1951): Profesor y dirigente social chileno de ideología antirrevisionista y de izquierda. Secretario general del Partido Comunista Chileno (Acción Proletaria). Ha sido candidato presidencial y es conductor de un programa en HispanTV.</p>
<p><strong>Representantes de coaliciones y partidos [No Activos]</strong></p>
<p>Gonzalo Winter&nbsp;(Frente Amplio / Unidad por Chile - oficialismo): Abogado y diputado joven, nacido en 1987, con militancia en el movimiento autonomista y político de izquierda más reciente. Su candidatura fue respaldada por el Frente Amplio tras las renuncias de otros candidatos en ese bloque. Winter enfatiza propuestas progresistas y renovación política dentro del oficialismo.</p>
<p>Carolina Tohá&nbsp;(Partido Por la Democracia / Unidad por Chile - oficialismo): Política experimentada y exalcaldesa de Santiago. Está vinculada al socialismo democrático y a la centroizquierda, con una carrera enfocada en la gestión municipal y el trabajo legislativo. Su candidatura representa la tradición y experiencia política dentro del bloque oficialista.</p>
<p>Jaime Mulet&nbsp;(Federación Regionalista Verde Social): Político regionalista nacido en 1956, con una trayectoria ligada a la defensa de la descentralización y temas sociales en regiones. Su postulación busca dar voz a los sectores más periféricos y resalta el enfoque territorial en las políticas públicas.</p>
</section>
<section id="el-capital-burocrático-de-los-aspirantes" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="el-capital-burocrático-de-los-aspirantes"><span class="header-section-number">1.1.2</span> El capital burocrático de los aspirantes</h3>
<p>Como describimos en artículos anteriores, el <strong>capital burocrático</strong>&nbsp;es el cúmulo de competencias, experiencia, conocimientos y relaciones que poseen los agentes dentro de una burocracia, y que les permite operar eficaz y legítimamente en el marco institucional estatal o corporativo. A partir de la sistematización de los cargos directivos según su posición en torno al poder ejecutivo es posible medir y comparar la experiencia de cualquier actor, partido o coalición política desde las guerras de Independencia hasta la actualidad. Por su puesto, es un esfuerzo metodológico que aun se encuentra en fase de desarrollo y se requieren aún varias pruebas y detección de errores para mejorar su calibración.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Elaborado por: n0dn | The linked data
</caption>
<thead>
<tr>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Aspirante
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Edad
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Género
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Comuna de nacimiento
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Coalición
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Partido
</th>
<th style="text-align:left;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Candidatura activa
</th>
<th style="text-align:right;font-weight: bold;color: cyan !important;background-color: rgba(3, 41, 60, 255) !important;">
Capital burocrático (kb
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Carolina Montserrat Toha Morales
</td>
<td style="text-align:right;">
60
</td>
<td style="text-align:left;">
Mujer
</td>
<td style="text-align:left;">
Santiago
</td>
<td style="text-align:left;">
Coalicion Unidad por Chile
</td>
<td style="text-align:left;">
PPD, PL, PDC y PS
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
1011
</td>
</tr>
<tr>
<td style="text-align:left;">
Ximena Cecilia Rincon Gonzalez
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:left;">
Mujer
</td>
<td style="text-align:left;">
Concepcion
</td>
<td style="text-align:left;">
Coalición Chile Vamos
</td>
<td style="text-align:left;">
Demócratas
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
879
</td>
</tr>
<tr>
<td style="text-align:left;">
Jaime Francisco Mulet Martínez
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Vallenar
</td>
<td style="text-align:left;">
Coalicion Unidad por Chile
</td>
<td style="text-align:left;">
Federación Regionalista Verde Social, Partido Regionalista
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
610
</td>
</tr>
<tr>
<td style="text-align:left;">
Jeannette Alejandra Jara Roman
</td>
<td style="text-align:right;">
51
</td>
<td style="text-align:left;">
Mujer
</td>
<td style="text-align:left;">
Conchali
</td>
<td style="text-align:left;">
Coalicion Unidad por Chile
</td>
<td style="text-align:left;">
PCCh, AH, SD, PPD, PS, PL, FAP, FRVS
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
594
</td>
</tr>
<tr>
<td style="text-align:left;">
Harold Alfred Mayne-Nicholls Sacul
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Antofagasta
</td>
<td style="text-align:left;">
Independiente
</td>
<td style="text-align:left;">
Independiente
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
570
</td>
</tr>
<tr>
<td style="text-align:left;">
Evelyn Rose Matthei Fornet
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:left;">
Mujer
</td>
<td style="text-align:left;">
Santiago
</td>
<td style="text-align:left;">
Coalición Chile Vamos
</td>
<td style="text-align:left;">
UDI, RN, Evopoli, Amarillos por Chile
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
469
</td>
</tr>
<tr>
<td style="text-align:left;">
Marco Enriques Ominami
</td>
<td style="text-align:right;">
52
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Santiago
</td>
<td style="text-align:left;">
Independiente
</td>
<td style="text-align:left;">
Independiente
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
321
</td>
</tr>
<tr>
<td style="text-align:left;">
Eduardo Antonio Artés Brichetti
</td>
<td style="text-align:right;">
74
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
San Vicente Tagua Tagua
</td>
<td style="text-align:left;">
Partido Comunista Chileno Accion Proletaria
</td>
<td style="text-align:left;">
PCCAP
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
273
</td>
</tr>
<tr>
<td style="text-align:left;">
José Antonio Kast Rist
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Santiago
</td>
<td style="text-align:left;">
Derecha Unida
</td>
<td style="text-align:left;">
PR, PSC
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
255
</td>
</tr>
<tr>
<td style="text-align:left;">
Franco Aldo Parisi Fernández
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Santiago
</td>
<td style="text-align:left;">
Partido de la Gente
</td>
<td style="text-align:left;">
Partido de la Gente
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
253
</td>
</tr>
<tr>
<td style="text-align:left;">
Gonzalo Rodolfo Winter Etcheberry
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Santiago
</td>
<td style="text-align:left;">
Coalicion Unidad por Chile
</td>
<td style="text-align:left;">
Frente Amplio
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
243
</td>
</tr>
<tr>
<td style="text-align:left;">
Johannes Maximilian Kaiser Barents von Hohenhagen
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:left;">
Hombre
</td>
<td style="text-align:left;">
Santiago
</td>
<td style="text-align:left;">
Derecha Unida
</td>
<td style="text-align:left;">
Partido Nacional Libertario
</td>
<td style="text-align:left;">
Si
</td>
<td style="text-align:right;">
156
</td>
</tr>
</tbody>
</table>
<p>Tabla 1. Datos generales de los aspirantes</p>
</div>
</div>
</section>
</section>
<section id="capital-burocrático-de-las-coaliciones" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="capital-burocrático-de-las-coaliciones"><span class="header-section-number">1.2</span> Capital burocrático de las coaliciones</h2>
<p>Iniciaremos con el capital burocrático de las coaliciones, es decir, con la suma de experiencias directivas de los aspirantes a la presidencia de cada uno de los partidos que componen las coaliciones electorales. El capital burocrático de las coaliciones partidistas mide la sumatoria de las experiencias en cargos directivos de los aspirantes que las componen, por lo que entre más actores existan mayor será el valor del capital burocrático de la coalición. Esto permite comparar las trayectorias de los candidatos dentro de los diferentes niveles y órganos del Estado así como de aquellas actividades fuera del Estado.</p>
<div class="cell">
<div class="cell-output-display">
<div id="dbctctmzin" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>@import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap");
#dbctctmzin table {
  font-family: Roboto, system-ui, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#dbctctmzin thead, #dbctctmzin tbody, #dbctctmzin tfoot, #dbctctmzin tr, #dbctctmzin td, #dbctctmzin th {
  border-style: none;
}

#dbctctmzin p {
  margin: 0;
  padding: 0;
}

#dbctctmzin .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 3px;
  border-top-color: rgba(255, 255, 255, 0);
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#dbctctmzin .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#dbctctmzin .gt_title {
  color: #333333;
  font-size: 30px;
  font-weight: bold;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#dbctctmzin .gt_subtitle {
  color: #333333;
  font-size: 16px;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#dbctctmzin .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#dbctctmzin .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#dbctctmzin .gt_col_headings {
  border-top-style: solid;
  border-top-width: 3px;
  border-top-color: rgba(255, 255, 255, 0);
  border-bottom-style: solid;
  border-bottom-width: 3px;
  border-bottom-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#dbctctmzin .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 80%;
  font-weight: bolder;
  text-transform: uppercase;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 6px;
  padding-bottom: 7px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#dbctctmzin .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 80%;
  font-weight: bolder;
  text-transform: uppercase;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#dbctctmzin .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#dbctctmzin .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#dbctctmzin .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 3px;
  border-bottom-color: rgba(255, 255, 255, 0);
  vertical-align: bottom;
  padding-top: 6px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#dbctctmzin .gt_spanner_row {
  border-bottom-style: hidden;
}

#dbctctmzin .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 80%;
  font-weight: bolder;
  text-transform: uppercase;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#dbctctmzin .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 80%;
  font-weight: bolder;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#dbctctmzin .gt_from_md > :first-child {
  margin-top: 0;
}

#dbctctmzin .gt_from_md > :last-child {
  margin-bottom: 0;
}

#dbctctmzin .gt_row {
  padding-top: 6px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#dbctctmzin .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 80%;
  font-weight: bolder;
  text-transform: uppercase;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#dbctctmzin .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#dbctctmzin .gt_row_group_first td {
  border-top-width: 2px;
}

#dbctctmzin .gt_row_group_first th {
  border-top-width: 2px;
}

#dbctctmzin .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#dbctctmzin .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#dbctctmzin .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#dbctctmzin .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#dbctctmzin .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#dbctctmzin .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#dbctctmzin .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#dbctctmzin .gt_striped {
  background-color: #F5F5F5;
}

#dbctctmzin .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#dbctctmzin .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#dbctctmzin .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#dbctctmzin .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#dbctctmzin .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#dbctctmzin .gt_left {
  text-align: left;
}

#dbctctmzin .gt_center {
  text-align: center;
}

#dbctctmzin .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#dbctctmzin .gt_font_normal {
  font-weight: normal;
}

#dbctctmzin .gt_font_bold {
  font-weight: bold;
}

#dbctctmzin .gt_font_italic {
  font-style: italic;
}

#dbctctmzin .gt_super {
  font-size: 65%;
}

#dbctctmzin .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#dbctctmzin .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#dbctctmzin .gt_indent_1 {
  text-indent: 5px;
}

#dbctctmzin .gt_indent_2 {
  text-indent: 10px;
}

#dbctctmzin .gt_indent_3 {
  text-indent: 15px;
}

#dbctctmzin .gt_indent_4 {
  text-indent: 20px;
}

#dbctctmzin .gt_indent_5 {
  text-indent: 25px;
}

#dbctctmzin .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#dbctctmzin div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="gt_heading header">
<td colspan="5" class="gt_heading gt_title gt_font_normal">Tabla 2. Aspirantes según su capital burocrático</td>
</tr>
<tr class="gt_heading even">
<td colspan="5" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Presidencia de Chile 2025</td>
</tr>
<tr class="gt_col_headings header">
<th id="Coalición" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" style="background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63" scope="col">Coalición</th>
<th id="Aspirante" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" style="background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63" scope="col">Aspirante</th>
<th id="prom_kb" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63" scope="col">Prom. Kb</th>
<th id="ranking_kb" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" style="background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63" scope="col">Ranking Kb<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="ranking_icon" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" style="background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63" scope="col">Capital burocrático<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Coalición">Coalicion Unidad por Chile</td>
<td class="gt_row gt_left" headers="Aspirante">Carolina Montserrat Toha Morales</td>
<td class="gt_row gt_right" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #80808033;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #808080;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
NA
</div>
</div>
</div></td>
<td class="gt_row gt_left" headers="ranking_kb">Alto</td>
<td class="gt_row gt_center" headers="ranking_icon" style="color: #28A745; font-size: 20px; font-weight: bold">▲</td>
</tr>
<tr class="even">
<td class="gt_row gt_left gt_striped" headers="Coalición">Coalición Chile Vamos</td>
<td class="gt_row gt_left gt_striped" headers="Aspirante">Ximena Cecilia Rincon Gonzalez</td>
<td class="gt_row gt_right gt_striped" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #97D83F33;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #97D83F;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
879
</div>
</div>
</div></td>
<td class="gt_row gt_left gt_striped" headers="ranking_kb">Alto</td>
<td class="gt_row gt_center gt_striped" headers="ranking_icon" style="color: #28A745; font-size: 20px; font-weight: bold">▲</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Coalición">Coalicion Unidad por Chile</td>
<td class="gt_row gt_left" headers="Aspirante">Jaime Francisco Mulet Martínez</td>
<td class="gt_row gt_right" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #1F978B33;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #1F978B;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
610
</div>
</div>
</div></td>
<td class="gt_row gt_left" headers="ranking_kb">Alto</td>
<td class="gt_row gt_center" headers="ranking_icon" style="color: #28A745; font-size: 20px; font-weight: bold">▲</td>
</tr>
<tr class="even">
<td class="gt_row gt_left gt_striped" headers="Coalición">Coalicion Unidad por Chile</td>
<td class="gt_row gt_left gt_striped" headers="Aspirante">Jeannette Alejandra Jara Roman</td>
<td class="gt_row gt_right gt_striped" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #20938C33;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #20938C;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
594
</div>
</div>
</div></td>
<td class="gt_row gt_left gt_striped" headers="ranking_kb">Alto</td>
<td class="gt_row gt_center gt_striped" headers="ranking_icon" style="color: #28A745; font-size: 20px; font-weight: bold">▲</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Coalición">Independiente</td>
<td class="gt_row gt_left" headers="Aspirante">Harold Alfred Mayne-Nicholls Sacul</td>
<td class="gt_row gt_right" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #228C8D33;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #228C8D;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
570
</div>
</div>
</div></td>
<td class="gt_row gt_left" headers="ranking_kb">Alto</td>
<td class="gt_row gt_center" headers="ranking_icon" style="color: #28A745; font-size: 20px; font-weight: bold">▲</td>
</tr>
<tr class="even">
<td class="gt_row gt_left gt_striped" headers="Coalición">Coalición Chile Vamos</td>
<td class="gt_row gt_left gt_striped" headers="Aspirante">Evelyn Rose Matthei Fornet</td>
<td class="gt_row gt_right gt_striped" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #2D708E33;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #2D708E;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
469
</div>
</div>
</div></td>
<td class="gt_row gt_left gt_striped" headers="ranking_kb">Alto</td>
<td class="gt_row gt_center gt_striped" headers="ranking_icon" style="color: #28A745; font-size: 20px; font-weight: bold">▲</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Coalición">Independiente</td>
<td class="gt_row gt_left" headers="Aspirante">Marco Enriques Ominami</td>
<td class="gt_row gt_right" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #42418633;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #424186;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
321
</div>
</div>
</div></td>
<td class="gt_row gt_left" headers="ranking_kb">Bajo</td>
<td class="gt_row gt_center" headers="ranking_icon" style="color: #DC3545; font-size: 20px; font-weight: bold">▼</td>
</tr>
<tr class="even">
<td class="gt_row gt_left gt_striped" headers="Coalición">Partido Comunista Chileno Accion Proletaria</td>
<td class="gt_row gt_left gt_striped" headers="Aspirante">Eduardo Antonio Artés Brichetti</td>
<td class="gt_row gt_right gt_striped" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #46307E33;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #46307E;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
273
</div>
</div>
</div></td>
<td class="gt_row gt_left gt_striped" headers="ranking_kb">Bajo</td>
<td class="gt_row gt_center gt_striped" headers="ranking_icon" style="color: #DC3545; font-size: 20px; font-weight: bold">▼</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Coalición">Derecha Unida</td>
<td class="gt_row gt_left" headers="Aspirante">José Antonio Kast Rist</td>
<td class="gt_row gt_right" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #472A7A33;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #472A7A;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
255
</div>
</div>
</div></td>
<td class="gt_row gt_left" headers="ranking_kb">Bajo</td>
<td class="gt_row gt_center" headers="ranking_icon" style="color: #DC3545; font-size: 20px; font-weight: bold">▼</td>
</tr>
<tr class="even">
<td class="gt_row gt_left gt_striped" headers="Coalición">Partido de la Gente</td>
<td class="gt_row gt_left gt_striped" headers="Aspirante">Franco Aldo Parisi Fernández</td>
<td class="gt_row gt_right gt_striped" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #48297933;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #482979;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
253
</div>
</div>
</div></td>
<td class="gt_row gt_left gt_striped" headers="ranking_kb">Bajo</td>
<td class="gt_row gt_center gt_striped" headers="ranking_icon" style="color: #DC3545; font-size: 20px; font-weight: bold">▼</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Coalición">Coalicion Unidad por Chile</td>
<td class="gt_row gt_left" headers="Aspirante">Gonzalo Rodolfo Winter Etcheberry</td>
<td class="gt_row gt_right" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #48257633;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #482576;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
243
</div>
</div>
</div></td>
<td class="gt_row gt_left" headers="ranking_kb">Bajo</td>
<td class="gt_row gt_center" headers="ranking_icon" style="color: #DC3545; font-size: 20px; font-weight: bold">▼</td>
</tr>
<tr class="even">
<td class="gt_row gt_left gt_striped" headers="Coalición">Derecha Unida</td>
<td class="gt_row gt_left gt_striped" headers="Aspirante">Johannes Maximilian Kaiser Barents von Hohenhagen</td>
<td class="gt_row gt_right gt_striped" headers="prom_kb"><div>
<div style="height: 20px;width:70px; background-color: #44015433;border-radius:5px;)">
<div style="height: 13px;width: 13px;background-color: #440154;display: inline-block;border-radius:4px;float:left;position:relative;top:17%;left:6%;">

</div>
<div style="display: inline-block;float:right;line-height:20px; font-weight: bold;padding: 0px 2.5px;">
156
</div>
</div>
</div></td>
<td class="gt_row gt_left gt_striped" headers="ranking_kb">Bajo</td>
<td class="gt_row gt_center gt_striped" headers="ranking_icon" style="color: #DC3545; font-size: 20px; font-weight: bold">▼</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="odd">
<td colspan="5" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> La intensidad del color representa la experiencia en cargos directivos del aspirante con respecto a la media histórica (1818-2022)</td>
</tr>
<tr class="even">
<td colspan="5" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> ▲ Alto (≥455 kb) | ■ Medio (440-454.99 kb) | ▼ Bajo (≤ 439.99 kb)</td>
</tr>
</tfoot>

</table>

</div>
<p>Tabla 2. Aspirantes según su capital burocrático</p>
</div>
</div>
<p>Como se aprecia en <span class="citation" data-cites="grap_coaliciones_kb">(<a href="#ref-grap_coaliciones_kb" role="doc-biblioref"><strong>grap_coaliciones_kb?</strong></a>)</span> los aspirantes de Coalición Unidad por Chile que representa al oficialismo y a los partidos de izquierda y centro izquierda (tanto de la nueva hisquierda encabezada por el presidente Boric como de la extinta Concertación que acumula a los partidos de centro izquierda) acumula principalemente Intra-burocrático con 1,044 kb lo que indica que predomina la experiencia en Ministerios de Estado, seguida de ella se encuentra la sub-burocrática que refiere la experiencia en Partidos Políticos y Alcaldias o Comunas con 589 kb, y en tercer lugar el capital para-burocrático con 567 kb los cuales abarcan principalmente el trabajo legislativo. Finalmente el capital exa-burocrático que incluye actividades empresariales y en sociedad civil con 258 kb. Lo anterior, muestra que los candidatos de la Coalición Unidad por Chile cuentan con amplia experiencia en labores ejecutivas del Estado, cuentan con una base partidista sólida y experiencia en el campo legislativo, todas ellas por encima de las labores empresariales o de sociedad civil.</p>
<p>Por su parte, la coalición Chile Vamos que representa a los partidos de derecha y extrema derecha, con fuertes vínculos en la dictadura de Augusto Pinochet, el gremialismo y en varios casos ex-militantes de la Unión Democrática Independiente (UDI) el partido de la herencia pinochetista, cuentan con mayor experiencia en el capital para-burocrático especialmente en las diputaciones federales, seguida del capital intra-burocrático ya todos ellos fueron ministros de Estado durante el gobierno de Sebastián Piñera como los casos de Eveline Matthei y Jose Antonio Kast.</p>
<p>El tercer grupo con mayor capital burocrático acumulado son los candidatos independientes con 891 kb. La mayoría de su capital burocrático se concentra en exa burocrático 651 kb, particularmente en el sector empresarial particularmente por Harlold Mayner quien se ha dedicado exclusivamente al sector empresarial y que es el único de los aspirantes sin experiencia en algún cargo público. La Coalición de Derecha Unida, en el cuarto puesto en la acumulación de capital burocrático, siendo el capital sub-burocrático que se refiere a la creación y dirección de partidos políticos acumula 243 kb, en tanto que los capitales para y exa tienen una proporción similar con 164 y 160 kbs respectivamente, lo que señala que dicha formación acumula la misma experiencia en el sector empresarial y en la legislatura. Finalmente, el Partico Comunista de Chile- Acción Proletaria y Partido de la Gente no forman ninguna coalición, sino que tienen un sólo representante, como se verá más adelante.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Aspirantes_Chile_2025_files/figure-html/grap_coaliciones_kb-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Gráfica 1. Acumulación de capital burocrático por coaliciones partidistas</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="capital-burocrático-por-persona" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="capital-burocrático-por-persona"><span class="header-section-number">1.3</span> Capital burocrático por persona</h2>
<p>La trayectoria política es el resultado de la intención, persistencia y capacidad de adaptación de las personas para lograr un objetivo propuesto desde temprana edad. El capital burocrático es un indicador de ese esfuerzo y capacidad en actividades directivas que le dotan del prestigio necesario para acceder a posiciones cada vez más estratégicas dentro del aparato de Estado que les permitan alcanzar los recursos necesarios para llevar a cabo los programas políticos y solventar temas de interés de su subred política. Al agruparlos por su kb con respecto a la media histórica que es de 455 kb<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, hallé 4 grupos de aspirantes que son Muy alto kb igual o mayor a 879 kb; alto 570 a 610 kb, medio 415-469 y bajo menor a 321 kb.</p>
<section id="muy-alto" class="level4" data-number="1.3.0.1">
<h4 data-number="1.3.0.1" class="anchored" data-anchor-id="muy-alto"><span class="header-section-number">1.3.0.1</span> <strong>Muy alto</strong></h4>
<p>En el caso de los aspirantes para ocupar la primera magistratura del Estado chileno, encontramos que Carolina Toha y Ximena Rincón son las personas que acumulan mayor capital burocrático con 1,011 kb y 879 kb como se aprecia en <span class="citation" data-cites="graph_Dist_cargos">(<a href="#ref-graph_Dist_cargos" role="doc-biblioref"><strong>graph_Dist_cargos?</strong></a>)</span>, que son el doble de la media histórica . En constraste Johanes Kaisser es el candidato con menor capital burocrático con 156 kb es decir, 299 kb por debajo del promedio histórico, mientras que la aspirante que mayormente se acerca al promedio es Eveline Matthei con 469 kb, tan sólo 14 puntos por encima del promedio. Carolina Toha y Ximena Rincón acumulan experiencia en casi todos los tipos de capital dentro del Estado que, salvo la presidencia, vicepresidencia, ejército y Suprema Corte, en el resto ha tenido cargos directivos, así como cargos fuera del Estado como en empresas privadas y sociedad civil, lo que se traduce en que ambas son las aspirantes con mayor experiencia burocrática dentro del Estado.</p>
<p>Lo notable de estas aspirantes que ya no partipan en la contienda por la presidencia, es que ambas están ligadas a la red política histórica a partir de familiares en el caso de Carolina Toha, ligada desde la adolescencia al Partido Socialista y cuyo padre José Toha fue Ministro de Defensa de Salvador Allende (1970-1973) y de la diplomática Victoria Morales, así como por su tío Jaime Toha quien fue ministro durante las administraciones de Salvador Allende, Patricio Aylwin y Eduardo Frei así como otros familiares que han ocupado cargos legislativos, diplomáticos y como funcionarios del Estado. Por su parte, Ximena Rincón ligada desde su juventud a la Democracia Cristiana, tiene a su hermano Ricardo Rincón como diputado y a su ex esposo Juan Carlos Latorre quien fuera legislador y subsecretario de Obras durante el gobierno de Eduardo Frei. En este sentido, ella forma parte del círculo cercano del expresidente Eduardo Frei Ruiz-Tagle (1994-2000)</p>
</section>
<section id="alto" class="level4" data-number="1.3.0.2">
<h4 data-number="1.3.0.2" class="anchored" data-anchor-id="alto"><span class="header-section-number">1.3.0.2</span> <strong>Alto</strong></h4>
<p>Por otras parte Jaime Mulet, Jeanet Jara y Harold Mayne registran kb similares con 610, 594 y 570 respectivamente, pero en su composición difieren ya que Mulet acumula mayor experiencia en cargos directivos y Jara en cargos dentro de diferentes Ministerio de Estado, lo que muestra que Jara cuenta con mayor experiencia en cargos ejecutivos que Mulet. En cambio, Mayne como ya fue señalado, acumula muchas experiencia en cargos directivos pero fuera del aparato de Estado, es decir en empresas privadas ligadas al fútbol y otros deportes, lo cual lo muestra su liderazgo en la gerencia privada pero muestra su inexperiencia en cargos públicos.</p>
<p>Los vínculos de Mulet se encuentran dentro de una subred de la DC, liderada por Adolfo Zaldivar quien tuvo un papel relevante junto a sus hermanos salidvar para la construcción de ese partido posterior al regreso a la democracia en 1989, pero que por motivos personales decidió abandonar ese partido, fundar el Partido Regionalista Independiente (PRI) y con ello jalar a su subred fuera de la DC, como es el caso de Mulet. De allí que su acción como actor política se funde en la negociación sin cuartel para mantenerse dentro del espectro político. Por su parte, Jeanet Jara quien actualmente es la candidata de la coalición oficialista Unidad por Chile, representa a los primeros cuadros surgidos de la unión de movimientos insurgentes de izquierda de la primera década del siglo XXI y que apoyaron la candidatura de Gabriel Boric. Jara, la segunda candidata a la presidencia del país por el Partido Comunista, despues de Gladys Marín, es una política con la mayor experiencia en cargos dentro del Ministerio del trabajo durante las administraciones de Michelle Bachelet y Gabriel Boric, lo que le permite contar con el respaldo de los partidos de izquierda de la coalición formada por la extinta Concertación y los nuevos partidos que apoyan al presidente Boric.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Aspirantes_Chile_2025_files/figure-html/graph_Dist_cargos-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Gráfico 2. Distribución de kb por aspirante</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="medio" class="level4" data-number="1.3.0.3">
<h4 data-number="1.3.0.3" class="anchored" data-anchor-id="medio"><span class="header-section-number">1.3.0.3</span> <strong>Medio</strong></h4>
<p>En esta clasificación se encuentran los casos de Evelin Matthei y José Antonio Kast, personajes ideológicamente cercanos así como dentro de la red política, ya que ambos tienen vínculos familiares y políticos surgidos durante la dictadura de Augusto Pinochet. En el caso de Evelin Matthei quien registra 469 kb, integrados principalmente por su trabajo legislativo, en partidos y en ministerios de Estado durante los gobiernos de Sebastián Piñera. Su padre, Fernando Matthei, quien fuera general del ejército chileno y ministro de Salud durante la dictadura de Pinochet y su esposo Jorge Desormeaux quien fuera director del Banco Central de Chile, le dotan de un prestigio dentro de la subred pinochetista, aunada a su participación en la fundación de Renovación Nacional donde se vinculó políticamente con Sebastian Piñera. Por su parte, Jose Antonio Kast, quien fuera militante de la UDI desde su juventud hasta 2016, es hijo Michael Kast Schindele del ex militante y soldado NAZI que partició en la Segunda Guerra Mundial, y de cuya ideología nunca abandonó, de hecho le ayudó para integrar a sus hijos Miguel y el propio Jose Antonio a la subred de la dictaruda pinochetista. Los hijos de ambos hermanos Kast también forman parte de la subred actual que dirige la extrema derecha chilena como son los casos de Felipe y Pablo Kast.</p>
</section>
<section id="bajo" class="level4" data-number="1.3.0.4">
<h4 data-number="1.3.0.4" class="anchored" data-anchor-id="bajo"><span class="header-section-number">1.3.0.4</span> <strong>Bajo</strong></h4>
<p>En este grupo se encuentran los candidatos independientes Marco Enriquez y el ex aspirante del Frente Amplio, Gonzalo Winter, así como los candidatos de los partidos Comunista-Acción Proletaria, Eduardo Artés, de la Gente de Franco Parisi y del ultra conservador Nacional Libertario de Johanes Kaiser. De estos cuatro, tres de ellos cuentan con experiencia mayor a 30 años en la política y que sin embargo no han logrado acumular mayores cargos directivos estratégicos dentro del aparato de Estado. Quizás la característica que los asimila sea su centralidad dentro de las subredes a las que pertenecen. Marco Enriquez que acumula 321 kb y quien es hijo de Miguel Enriquez , fundador del (Movimiento Izquierda Revolucionaria) MIR y militante vinculado a la red de Allende, no logró fortalecer su vínculo con la subred del partido Socialista ni con la Concertación lo que ha llevado a postularse por su cuenta más de cuatro veces por la presidencia quedando en puestos alejados de los tres primeros lugares.</p>
<p>Por su parte Gonzálo Winter con 243 kb y quien con 38 años es el aspirante más jóven aunque ya no se encuentra activo, surge de la red de movimientos estudiantiles insurgentes surgidos en la primera década de los 2000, y quien se encuentra vinculado por esta red al presidente Boric. En contraste, Eduardo Artés que acumula 273 kb, es el candidato con mayor edad y con una amplia experiencia que parte desde el gobierno de Salvador Allende como dirigente estudiantil comunista, y que tras el regreso a la democracia ha participado sin éxito en elecciones parlamentarias y presidenciales, siendo ésta su tercera participación desde las elecciones de 2017. De igual manera que Enriquez y Artés, para Franco Parisilas elecciones de 2025 representan su tercera contienda por la presidencia, aunque a diferencia de ellos sus porcentajes de votación superan el 10% en las elecciones de 2013 y 2021.</p>
<p>A pesar de ello, Parisi, candidato de Partido por la Gente que él mismo creó en 2021, acumula 253 kb, tan sólo 10 puntos por encima de Winter el candidato más jóven. Finalmente, Johannes Kaiser que acumula 156 kb, es descendiente de colonos alemanes que emigran a Chile en la década de 1930, y cuyo padre Hans Chiristian Kaiser inició su carrera política en los conservadores Partido Nacional y posteriormente en la UDI. Sin embargo, sus hermanos y primos se han desempeñado en diferentes cargos públicos dentro de la subred de la UDI cercana al pinochetismo actual como son los casos de sus hermanos Axel (ideólogo, escritor y conferensista neoconservador), Vanessa Olimpia (consejala, youtuber y columnista), Leif Magnus (líder de la Asociación Chilena del Rifle).</p>
</section>
</section>
</section>
<section id="la-lucha-entre-redes-políticas-el-clan-emergente-vs-la-casta-hereditaria" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> La lucha entre redes políticas: El <em>clan emergente</em> vs la <em>casta hereditaria</em></h1>
<p>La diferencia más importante de un político además de su capital burocrático es su centralidad dentro de la red política histórica. La política es el uso instrumental de los vínculos de personajes con capitales social, económico y burocrático lo suficientemente estratéfico para movilizar el capital social de grandes conglomerados. Para mantener la cumulación de dicho capital político los personajes se organizan en torno a diferentes estructuras que dependen de las fuentes de poder que las vinculan. En el caso de los candidatos a la presidencia de Chile para 2025 se encuentran dos tipos de estructuras que compiten entre sí como clases dirigentes:</p>
<ul>
<li>las castas heredada por vínculos familiares, políticos, empresariales que conformaron una clase dirigente durente la dictadura de Pinochet, la Concertación y el gobierno de Sebstián Piñera</li>
<li>los clanes vinculados por trabajo meramente político y empresarial que no se han estructurado como clase dirigente.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Castas y clanes
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>Casta</strong>: sistema de estratificación social mucho más rígido y cerrado, donde el estatus social y las identidades están determinadas hereditariamente y se mantienen a través de reglas de endogamia estricta. En las castas, la pertenencia y las oportunidades sociales dependen del nacimiento, y los grupos están organizados en jerarquías fijas con limitaciones sociales, legales y culturales para la movilidad entre ellas. Este sistema es característica de sociedades con divisiones sociales muy estructuradas, como el sistema de castas en India o sistemas similares de estratos sociales rígidos, donde la casta define la posición social, los roles y las interacciones con otros grupos</p></li>
<li><p><strong>Clan</strong>: grupo social basado principalmente en la descendencia común, generalmente en sociedades donde lazos de parentesco y consanguinidad constituyen la unidad fundamental de organización política y social. Los clanes funcionan en sistemas segmentarios o de linaje, donde la solidaridad interna y la identidad colectiva se construyen sobre la genealogía compartida, pudiendo incluir reglas específicas de alianza y conflicto con otros grupos. Son grupos relativamente abiertos y flexibles, donde el parentesco es importante para la cohesión y la expresión de la vida política, pero sin una jerarquía rígida de estatus o privilegios heredados.</p></li>
</ul>
</div>
</div>
<p>La red política chilena se caracteriza por la densidad de sus vínculos estables que van desde el útlimo tercio del siglo XVIII por la clase colonial española (vascos) y criollos chilenos, la cual participó activamente en la construcción de la República que surgió de la guerra de independencia en el primer tercio del siglo XIX y que se acomodó como nueva clase dominante, junto con migrantes ingleses, norteamericanos, franceses, croatas y alemanes que transitaron su acumulación de capital económico del fundo a las industrias y a la banca <span class="citation" data-cites="historia2017">(<a href="#ref-historia2017" role="doc-biblioref"><strong>historia2017?</strong></a>)</span>. Durante todo el siglo XIX, la red política chilena comenzó a consolidarse en torno a los vínculos de los antiguos latifundios con los nuevos industriales mineros y comerciantes ultramarinos de Valapariso, y conformaron una red política que incluyó además de los vínculos económicos, su raigambre en las guerras de independencia, golpes de Estado, la conformación de partidos y su participación en los diferentes gobiernos conservadores y liberales<span class="citation" data-cites="collier1999">(<a href="#ref-collier1999" role="doc-biblioref">Collier &amp; Sater, 1999</a>)</span>. Aunado a ello, los militares tuvieron un papel relevante especialmente en las diferentes guerras contra Perú y España.</p>
<p>Para el siglo XX, ya estaba conformada la red política en torno a castas dominantes en torno a las cuales se configuraban los diferentes gobiernos, independientemente del partido del presidente, lo cual dotó a la red de cierta estabilidad toda vez que existían altos grados de agrupamiento al interior de la red política hasta 1973. El golpe de Estado que conllevó a la dictadura militar de Augusto Pinochet, destaca de los anteriores golpes por la intervención directa del gobierno de Estados Unidos y coordinada dentro de su esquema colonial denominado “Plan Cóndor”&nbsp;el cual abarcó toda Latinoamérica y el Caribe. La dictadura de Pinochet reconfiguró la antigua clase política del siglo XX, y conformó una red emergente proveniente de las clases empresariales y militares conservadoras, las cuales se vinculan en torno a grupos familiares que conformaron la UDI y RN.</p>
<p>El retorno a la democracia trajo de vuelta a la red política tradicional, la cual derribó las barreras ideológicas del siglo XX (Demócrata Cristianos, Radicales, Socialistas, Comunistas) para llevarlos como bloque partidista que duraría 16 años en la presidencia del país. Desde 1989 hasta la actualidad las castas surgidas de la junta militar y aquellas con tradición política durante el siglo XX, compitieron por la presidencia en dos bloques de partidos: Concertación&nbsp;y Pinochetistas. Pero en 2006 emergió una nueva red política proveniente de las clases medias y populares vinculadas por las escuelas y universidades, quienes a través de la organización colectiva lograron ganar la presidencia en 2022 bajo el liderazgo de Gabriel Boric. Esta red emergente se relaciona en torno a clanes vinculados por el trabajo político en los gobiernos de la Concertación, particularmente en los dos periodos de Michelle Bachelet y por otro, en los nuevos movimientos estudiantiles y sociales vinculados a Boric.</p>
<section id="dinámica-del-capital-burocrático" class="level3" data-number="2.0.1">
<h3 data-number="2.0.1" class="anchored" data-anchor-id="dinámica-del-capital-burocrático"><span class="header-section-number">2.0.1</span> Dinámica del capital burocrático</h3>
<p>Cómo se aprecia en el gráfico 3, el capital burocrático de los aspirantes a la presidencia de Chile desde 1808 hasta 2021 ha sido altamente volátil durante todo el siglo XIX hasta el primer tercio del siglo XX. A partir de las elecciones de 1938 y hasta 1970 el capital burocrático de los candidatos registró poca variación, lo que señala lo similares que llegaron a ser entre ellos a pesar del partido al que pertenecieran. Tras el regreso a la democracia la volatilidad volvió a ser alta, siendo las elecciones de 2009 donde se registró una mayor diferencia de entre los candidatos. Sin embargo a partir del 2013 el kb de los candidatos registró una media inferior a la media histórica, lo que indica un cambio en la acumulación de cargos directivos antes de llegar a ser candidatos.</p>
<p>Esta nueva subred se juega su permanencia para los próximos 20 años contra el retorno de la antigua casta pinochetista (UDI, RN, Libertarios, Republicanos). Las subredes que conforman la Coalición Unidad por Chile es la que muestra mayor capital burocrático necesario para demostrar sus capacidad de dirigir el aparato de Estado y continuar con su reforzamiento de la mano de Jeanette Jara, seguido por la Coalición Chile Vamos cuyo retorno podría echar abajo los avances en materia social si José Antonio Kast logra la mayoría en la primera vuelta.</p>



</section>
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referencias</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-collier1999" class="csl-entry" role="listitem">
Collier, S., &amp; Sater, W. F. (1999). <em>Historia de Chile, 1808-1994</em>. Cambridge University Press.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Notas</h2>

<ol>
<li id="fn1"><p>El estudio sobre el capital político de los aspirantes a la presidencia de Chile desde el proceso de independencia hasta 2022 será presentado próximamente en una publicación de revista indexada.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/n0dn\.github\.io\/n0dn\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2021-2026 n0dn | The linked Data. Todos los derechos reservados.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/n0dn_">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/norberto-bustos/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="mailto:n0dn.info@proton.me">
<p>n0dn.info@proton.me</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>